### PR TITLE
fix(menu,tooltip): Ensure subscription exists before unsubscribing.

### PR DESCRIPTION
**Pull request by trshafer**

### CODE REVIEW

**Comment by trshafer** [comment]
I'm having issues running the tests, I receive this error:
```
Finished ':build:test:vendor' after 1.22 s
node_modules/@types/jasmine/index.d.ts(39,38): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
node_modules/@types/jasmine/index.d.ts(39,46): error TS2304: Cannot find name 'keyof'.
node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.
':build:components:spec' errored after 4.08 s
```

**Comment by dahaupt** [comment]
@trshafer I've already opened up an issue for that. (#3074)

**Comment by trshafer** [comment]
I have added tests. Please take a look.

**Comment by kara** [comment]
I'm actually not sure we should change this. The scroll subscription and the tab subscription will always exist once the menu / tooltip are created. The reason the unit test can fail is because `fixture.detectChanges()` is not being called. This means change detection doesn't run and none of the init hooks are executed as they would in a real environment.

In this case, I think the test *should* fail. Testing menu or tooltip without allowing init hooks to run is inaccurate and could cause harder to debug test failures down the line.  @mmalerba, thoughts?

**Comment by mmalerba** [comment]
@kara Yep agreed, I didn't realize that in the normal lifecycle init was guaranteed to be called before destory. In that case i agree that the real issue here is that the tests are not simulating the true lifecycle of the component.

**Comment by trshafer** [comment]
Not having this code made our app more difficult to debug. We had an error when rendering, and the error was hidden by not checking for these subscriptions. a "cannot call .unsubscribe on undefined" error was blocking our actual application error.

**Comment by trshafer** [comment]
Other files have checks that the subscription is created: https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L271
https://github.com/angular/material2/blob/master/src/lib/core/overlay/overlay-directives.ts#L272

**Comment by kara** [comment]
If anything, I think those other checks should probably be removed for the same reason. Can you give us more information about hiding errors though? Typically they'd be thrown first.

**Comment by trshafer** [comment]
The issue is that one of our components threw an error on another init. The tooltip init had not run but had been constructed. The tooltip component was destroyed before the component which threw the error, so the exception which we received as in the tooltip instead of in our component. This made our application harder to debug.

There are other examples in angular core:
https://github.com/angular/angular/blob/master/modules/%40angular/platform-server/src/http.ts#L70
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L329

There are also examples of them not checking if the subscription exists.

**Comment by kara** [comment]
OK, we don't want to be hiding errors. In that case, LGTM.

**Pull request merged**
