### PR TITLE
chore(accordion): move CdkAccordion to @angular/cdk

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Comment by kara** [comment]
@josephperrott Can you take a look at the CI failures? The linter is unrelated (Miles is working on it), but the Saucelabs / Browserstack ones look like they are

**Comment by josephperrott** [comment]
@kara CI failures have been taken care of.  Should be good to go.

**Comment by kara** [comment]
@josephperrott Rebase too?

**Comment by josephperrott** [comment]
@kara Rebased.

**Pull request merged**
