### PR TITLE
docs: mention index.js changes in changelog

### PR DESCRIPTION
**Pull request by jelbourn**
R: @hansl 

Related #1190

### CODE REVIEW

**Comment by DevVersion** [comment]
Also good to mention that the typings are now based on `2.0.0` ?

**Comment by jelbourn** [comment]
@DevVersion added

**Comment by DevVersion** [comment]
@jelbourn Cool, we could probably move that also to the readme, but the new docs look good for me.

**Comment by kara** [comment]
LGTM

**Pull request merged**
