### PR TITLE
refactor(menu): remove 6.0.0 deletion targets

### PR DESCRIPTION
**Pull request by crisbeto**
Removes the menu APIs that were marked for deletion in 6.0.0.

BREAKING CHANGES:
* `mat-menu-trigger-for` which was deprecated in 5.0.0 has been removed. Use `matMenuTriggerFor` instead.
* `onMenuOpen` which was deprecated in 5.0.0 has been removed. Use `menuOpened` instead.
* `onMenuClose` which was deprecated in 5.0.0 has been removed. Use `menuClosed` instead.
* `_focusMonitor` parameter in the `MatMenuTrigger` constructor is now required.
* `close` which was deprecated in 5.0.0 has been removed. Use `closed` instead. Also applies to custom menus that implement the `MatMenuPanel` interface.
* `classList` which was deprecated in 5.0.0 has been removed. Use the `panelClass` property or pass in the classes via the `class attribute.
* `_startAnimation` which was deprecated in 5.0.0 has been combined with `_resetAnimation`.
* `_focusMonitor` and `document` parameters in the `MatMenuItem` constructor are now required.

### CODE REVIEW

**Comment by jelbourn** [comment]
Caretaker note: we need to remove google usages of the old API. This might require a cleanup before syncing this PR.

**Comment by jelbourn** [comment]
@crisbeto can you rebase?

**Comment by crisbeto** [comment]
Rebased @jelbourn. Also added another breaking change from #9794 that changes the signature of `MatMenuPanel.closed`.

**Comment by jelbourn** [comment]
@crisbeto can you break the `MatMenuPanel` change into a separate PR? That one is harder to do since it doesn't have a backwards compatible version.

**Comment by jelbourn** [comment]
@crisbeto Actually, on second thought, we can't actually change that one since it hasn't had a deprecation period.

**Comment by crisbeto** [comment]
Didn't we do a recent change that modified the signature though? In https://github.com/angular/material2/pull/9794 we changed the signature to include `| 'tab'` which would cause a compilation error as well.

**Comment by jelbourn** [comment]
Whoops:
https://www.typescriptlang.org/play/#src=interface%20Panel%20%7B%0A%20%20%20%20readonly%20closed%3A%20Array%3C'click'%20%7C%20'keydown'%20%7C%20'tab'%3E%0A%7D%0A%0Aclass%20MyPane%20implements%20Panel%20%7B%0A%20%20%20%20readonly%20closed%3A%20Array%3C'click'%20%7C%20'keydown'%3E%3B%0A%7D%0A%0Aconst%20p%20%3D%20new%20MyPane()%3B%0A%0A

**Comment by crisbeto** [comment]
Reverted the `MatMenuPanel` changes and set a deletion target for 7.0.0 @jelbourn.

**Comment by mmalerba** [comment]
@crisbeto you're still renaming the `MenuPanel` property `close` to `closed`, you need to either alias or just leave it as `close`

**Comment by crisbeto** [comment]
We had a deletion target for `close` @mmalerba, however it was inside the `menu-directive.ts`.

**Comment by mmalerba** [comment]
But we didn't have a `closed` for people to switch to (also this causes many failures in google3 that I'm not going to be able to track down before we release 6.0, so I won't be able to merge the rest of the PR unless you revert it)

**Comment by andrewseguin** [comment]
This will end up needing to be pushed to v7 - there was a significant amount of test failures internally that we do not have the bandwidth to fix and get approvals for.

**Comment by crisbeto** [comment]
Closing since these changes have been left for 7.0.

**Pull request closed without merging**
