### PR TITLE
build: add package name to AMD modules

### LINKED ISSUE #10142: UMD distributions have anonymous modules
Under Bazel, our devserver expects to be able to concatenate all the JS, meaning we can't rely on path information in XHRs to know what name each module has.

I fixed this for Angular in https://github.com/angular/angular/commit/82e49230ff80fe716f2c2aff3fe638bdc96c57ca
We should do the same thing for material distributions.

(Note, users could instead use some other loader like system.js to bring in UMD dependencies that don't provide a name, but this is a bunch of extra complexity. We should make the Bazel use case simple for libraries we control.)

### PR DESCRIPTION
**Pull request by DevVersion**
* Fixes that the UMD bundles, which use the `define` function in AMD mode, don't have a module name. This feature has been added in later versions of Rollup, so we had to upgrade. By comparing with the previous UMD bundles, the bundles still seem to work properly (also in our demo-app).

Fixes #10142

### CODE REVIEW

**Comment by jelbourn** [comment]
Can you test this against the docs site as well?

**Comment by DevVersion** [comment]
Does the docs site use SystemJS? If I remember correctly, it just uses the Angular CLI to build using Webpack.

**Comment by DevVersion** [comment]
Just noticed, that I added LGTM myself. Should have been `needs review`

**Comment by jelbourn** [comment]
I assumed as much

**Pull request merged**
