### PR TITLE
build: consistent line breaks for css files

### PR DESCRIPTION
**Pull request by crisbeto**
Bumps to stylelint 9.5.0 and enables the line break checking for CSS files.

### CODE REVIEW

**Comment by jelbourn** [comment]
Removing `merge safe` since the last time we removed bad line endings from Google we ran into some problems.

**Comment by jelbourn** [comment]
Passes presubmit, just needs rebase

**Comment by crisbeto** [comment]
Rebased.

**Comment by jelbourn** [comment]
Is the lint error on this one real?

**Comment by crisbeto** [comment]
Seems like it is. I got something similar on another PR, but never figured out why. It's fixed now.

**Pull request merged**
