### PR TITLE
build: switch to yarn

### PR DESCRIPTION
**Pull request by DevVersion**
Switches away from `package-lock.json` to `yarn.lock` because the NPM lock files are not platform independent and change based on `optionalDependencies` that can be installed.

Since the lock file always changes after NPM install on CircleCI, the cache key will be always different, and therefore never available for the next commit that runs on the CI.

**Note**: This is based on top of #13359 and should be merged once #13359 has been merged.

### CODE REVIEW

**Comment by DevVersion** [comment]
This should be ready now. The e2e failure is unrelated and should be fixed with #13376

**Comment by jelbourn** [comment]
@DevVersion could you rebase?

**Comment by DevVersion** [comment]
@jelbourn Should be good now. Let's wait for CircleCI to finish.

**Comment by DevVersion** [comment]
This one is good to go now.

**Comment by alexw10** [comment]
I am curious, why did you guys make the move to yarn?

**Pull request merged**
