### PR TITLE
chore: reorganize cdk/a11y directory structure

### PR DESCRIPTION
**Pull request by crisbeto**
* Since the `@angular/cdk/a11y` has grown a lot, it's becoming harder to navigate. These changes distribute the files into directories similarly to how we do it in `overlay`.
* Removes the individual imports from the focus trap tests in favor of importing the `A11yModule`.

### CODE REVIEW

**Comment by josephperrott** [comment]
needs rebase

**Comment by crisbeto** [comment]
Rebased.

**Comment by jelbourn** [comment]
@crisbeto Passes google presubmit, can merge as soon as it's rebased... again (sorry)

**Comment by crisbeto** [comment]
Rebased,

**Comment by jelbourn** [comment]
Looks like there's a build error now

**Comment by crisbeto** [comment]
Rebased and fixed a couple of wrong imports.

**Pull request merged**
