### PR TITLE
build: disallow namespace usage and bump stylelint

### PR DESCRIPTION
**Pull request by crisbeto**
* Enables a tslint rule that will prevent us from using namespaces. Based on the discussion in #8971.
* Bumps to the latest stylelint version.

### CODE REVIEW

**Comment by josephperrott** [comment]
@crisbeto Please rebase

**Comment by crisbeto** [comment]
Rebased @josephperrott.

**Comment by josephperrott** [comment]
@crisbeto I'm sorry, one more rebase

**Comment by crisbeto** [comment]
Rebased.

**Pull request merged**
