### PR TITLE
fix(): OnPush does not work for the SidenavLayout.

### PR DESCRIPTION
**Pull request by hansl**

### CODE REVIEW

**Comment by hansl** [comment]
@jelbourn: For Layout it's probably fine (performance-wise). I understand what's going on here and it's possible to fix it with `OnPush` strategy, but just not as elegant as the default strategy.

**Comment by jelbourn** [comment]
What's the TL;DR why push state doesn't work?

**Comment by hansl** [comment]
I've added a comment for this. PTAL.

**Comment by jelbourn** [comment]
LGTM

**Pull request merged**
