### PR TITLE
docs(table): include limitations on passing data into table

### PR DESCRIPTION
**Pull request by jesscrees**
Update documentation to include that pagination won’t work when passing data into table from 
parent component.

### CODE REVIEW

**Comment by andrewseguin** [comment]
Can you provide a Stackblitz example of what isn't currently working with this limitation?

**Comment by jesscrees** [comment]
Here is the example you requested: [https://stackblitz.com/edit/angular-rduhea](https://stackblitz.com/edit/angular-rduhea).

In this example, the data doesn't show at all. The issue I came across at work was that all the data showed and the paginator had no effect on it but I couldn't reproduce that in stackblitz. The only difference I can remember between the stackblitz example and my code is that my code made a call to an api and returned an observable which I subscribed to in the parent component to get the data. When I made that same call in the table component instead of the parent, it worked completely fine.

**Comment by bboehm86** [comment]
Well I don't think this a documentation issue of the table :-) You might want to take a look at the [angular lifecycle hooks docs](https://angular.io/guide/lifecycle-hooks). When you are creating your `dataSource` the `dataFromParent` will always be `undefined` at the constructor stage. Use a setter on your `@Input()` like:
 ```
@Input() set dataFromParent(data: any) {
  this.dataSource.data = data;
}
 ```
or use `ngOnChanges()`:
 ```
 ngOnChanges(simpleChange: SimpleChanges) {
    if ('dataFromParent' in simpleChange) {
      this.dataSource.data = simpleChange.dataFromParent.currentValue;
    }
  }
```
to update your `dataSource`.

**Comment by jesscrees** [comment]
Thank you for the explanation, I really appreciate it!

**Pull request closed without merging**
