### PR TITLE
chore(chips): update API per #6677

### PR DESCRIPTION
**Pull request by amcdnl**
Addresses #6677 for Chips

Changes:
- `select` to `selectionChange`
- `deselect` to `deselected` - @jelbourn - what do you think about making this `deselection`?
- `destroy` to `destroyed`
- `remove` to `removed`

### CODE REVIEW

**Comment by willshowell** [comment]
These selection list changes are probably relevant: https://github.com/angular/material2/pull/6901

**Comment by amcdnl** [comment]
@jelbourn - I like that much better. Updated. What about `removed`, can that go?

**Comment by jelbourn** [comment]
`removed` should stay AFAIK- why would you want to get rid of it?

**Comment by amcdnl** [comment]
@jelbourn - It was unclear to me how it differs from `delected`.

**Comment by tinayuangao** [comment]
@amcdnl could you please rebase?

**Comment by amcdnl** [comment]
This has diverged so much, I'm going to redo this in a new PR.

**Pull request closed without merging**
