### PR TITLE
fix(platform): don't shadow `window`

### PR DESCRIPTION
**Pull request by jelbourn**

### CODE REVIEW

**Comment by mmalerba** [comment]
Is this to fix a bug or fix some typescript error? I think `declare ...` just gets stripped out of the JS output.

**Comment by jelbourn** [comment]
It was causing a Googler a problem during a migration due to an extern; I like this approach more anyway, rather than aliases `window` like it was.

**Comment by mmalerba** [comment]
lgtm

**Comment by jelbourn** [comment]
In Google everything is indeed consumed directly from sources

**Comment by DevVersion** [comment]
I see. Then it makes total sense why the issue appears :)

**Pull request merged**
