### PR TITLE
docs: fix extra "," in the Theming block

### PR DESCRIPTION
**Pull request by sharikovvladislav**

### CODE REVIEW

**Comment by sharikovvladislav** [comment]
I signed it!

**Comment by sharikovvladislav** [comment]
@willshowell oh. I didn't not know this. I am sorry. But well.. Live and learn. Thank you for this. I think I should decline the PR now, right?

**Comment by jelbourn** [comment]
The comma is intentional and correct (as @willshowell explained above)

**Comment by sharikovvladislav** [comment]
@jelbourn @willshowell okay!

@willshowell thank you very much for your explanation :) 

we have a bit different rules and I didn't know about this

**Pull request closed without merging**
