### PR TITLE
refactor: remove css transform utility

### PR DESCRIPTION
**Pull request by crisbeto**
The `applyCssTransform` utility is no longer necessary since none of the browser we support need a prefix.

### CODE REVIEW

**Comment by jelbourn** [comment]
@crisbeto this PR shows up as a clean merge on github but has conflicts when we try to sync it. Could you rebase?

**Comment by crisbeto** [comment]
Rebased.

**Comment by jelbourn** [comment]
This is really weird. Our tool that pulls in PRs keeps saying it can't find the ref for this one. Try closing this and opening a new PR?

**Comment by crisbeto** [comment]
Closing in favor of #9571.

**Pull request closed without merging**
