### PR TITLE
build(npm): Upgrade to Angular2@2.0.0-beta.7

### PR DESCRIPTION
**Pull request by JayKan**
Update to Angular2@2.0.0-beta.7. Also, bump rxjs@5.0.0-beta.2 and zone.js@0.5.15 to resolve siblings' peerDependencies requirements

### CODE REVIEW

**Comment by hansl** [comment]
Is this ready for review?

Considering Angular2 is now on beta.8 and will be on beta.9 tomorrow, could you at least push to beta 8? There's not really any features we want but it's always nice to make sure it works without regressions.

On a separate note, please rebase your branch as there are some document changes that should not appear in this PR.

Cheers :D

**Comment by JayKan** [comment]
Hi @hansl,

I've updated to angular2@2.0.0-beta.8. All npm scripts were running success locally, however, I can see a build error from Travis CI, can't really reproduce the same error. Any ideas what's going on with this build error? 

Build error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

Other than that, I think this is ready for review. Thanks for the quick reply, really appreciate your help and feedback.

Thanks,
Jay Kan

**Comment by hansl** [comment]
Okay. Start by smashing your commits into a single one using this guide: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html. We want to only have a single commit by PR.

We also need you to rebase everything on the latest `master`. I see you rebased your branch but not your master, so the diff shows changes that are not part of this PR.

Finally, you want to sign the CLA. This is required for any contributions with Google open source projects.

Once these things are done I'll approve it and merge it myself. Thanks for taknig the time for this!

**Comment by JayKan** [comment]
So I've squashed my last 4 commits to one and I've also rebase my master branch as well.

Also, I've signed the CLA yesterday already not sure why I still need one. Please find attached screenshot for my CLA.

Please let me know if there's anything else I need to do, thanks!
cla

**Comment by hansl** [comment]
The problem is the CLA hasn't been signed for travis (on this PR). That's because you still have 3 commits.

Again, could you properly rebase on top of the master branch of this repo, and rebase your master on the master branch of this repo, to get rid of the 2 commits that are not relevant to this PR. If you need help I'm on gitter right now and can help you do it.

**Comment by jelbourn** [comment]
You also have to leave a comment that says `I signed it!` for the CLA bot to pick it up.

**Comment by hansl** [comment]
Oh I see what's going on.  You're from an invalid branch state, where the merge commit from @traviskaufman wasn't removed. I had to force push master to fix this, and you apparently fetched the history for this branch while it was in an invalid state.

Could you do this PR again from a clean master?  This could be fixed but for such a simple PR it's just better to redo it.

**Comment by hansl** [comment]
I'll close this now; just do a new PR for this and I'll LGTM it right away.

**Comment by JayKan** [comment]
Thanks for your quick reply @hansl, I'll do a new PR :)

**Pull request closed without merging**
