### PR TITLE
fix(radio-button): Radio buttons are not tab stops in Safari

### PR DESCRIPTION
**Pull request by trik**

### CODE REVIEW

**Comment by trik** [comment]
I signed it!

**Comment by robertmesserle** [comment]
Thanks for your contribution!  However, this issue was fixed as part of this PR: https://github.com/angular/material2/pull/415

**Comment by trik** [comment]
@robertmesserle what about this one? https://github.com/angular/material2/pull/436/commits/d56946ad6ca8d41a77dc4e6118361f7926bffd78

sorry, i had to make a different pr, it refers #327

**Comment by robertmesserle** [comment]
@trik We do still need a fix for this, but when I tried applying that commit to master and running the tests, it doesn't appear to fix the bug.  Were there other changes in one of the other commits required to make this work?

**Comment by trik** [comment]
@robertmesserle no, only that one.. why it doesn't fix? in then unit test i set a value for the radio group model and i get one button selected, then i set the model to null and all buttons are de-selected

**Comment by robertmesserle** [comment]
The failure I get is on the test you added.  It needed the following line:

```ts
this._radios.forEach(radio => radio.checked = false);
```

Without that, it never actually unchecked any of the child radio buttons.

**Comment by robertmesserle** [comment]
Ah, I see why your tests weren't failing.  Your tests were never running.

There was a bug in the radio button tests where `fakeAsync` was wrapped around a function, which returns a new function - but that new function is never called.  So your tests would have passed regardless of what they checked.  (This was an issue with all tests in radio-button and is being fixed now by @jelbourn).

There were some other changes required to make this work as well.  I'll open a PR with the working changes and mention you in it.

**Pull request closed without merging**
