### PR TITLE
feat(tabs): add theming and ability to set background color

### LINKED ISSUE #1362: [Tabs] Inverted md-tabs style
#### Bug, feature request, or proposal:

Feature enhancement
#### What is the expected behavior?

I would like tabs with same background as toolbar when they are next to each other. We could switch background and color properties (it could be a new md-tabs property).  You see this style in [Google Material Design](https://material.google.com/components/tabs.html).
#### What is the current behavior?

Now md-tabs just has the option of change color (which changes text color and ink bar), instead of setting the background.
#### What are the steps to reproduce?

Not applicable
#### What is the use-case or motivation for changing an existing behavior?

More consistency between toolbar and tabs. Developer might choose between light (text color) and dark (background color) versions.
#### Which versions of Angular, Material, OS, browsers are affected?

Latest
#### Is there anything else we should know?

Just a `reverse-style="true"` attribute might work well.

### LINKED ISSUE #2908: [tabs] md-tab-group theming
bug
 theming of tabs

What is the expected behavior?
`md-tab-group color="primary" ` set primary colors

What is the current behavior?
no color changed

 What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/K3yt0CYqZsIjrpflkcqu?p=preview

Which versions of Angular, Material, OS, browsers are affected?
browsers all, angular 2.4.3, material 2.0.0-beta.1,

### LINKED ISSUE #5014: tabs customization
#### Bug, feature request, or proposal:
Tabs cannot be customized to have a different background, ripple, bottom bar and text color or it's not clear how to do it

#### What is the expected behavior?
have a way to change the colors

#### What is the current behavior?
can't find a way to do it

#### What are the steps to reproduce?
using a md-tab-group results in a white background not a colored one with white text, how to change?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://embed.plnkr.co/o077B6uEiiIgkC0S06dd/

#### What is the use-case or motivation for changing an existing behavior?
customization

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, Material: latest

#### Is there anything else we should know?
No

### PR DESCRIPTION
**Pull request by willshowell**
Fixes #1362
Fixes #2908
Fixes #5014

### CODE REVIEW

**Comment by willshowell** [comment]
I definitely need to rework this to cut down on how much css is generated

**Comment by ocarreterom** [comment]
How about something like:
```sass
$theme-colors: (
  primary: $primary,
  accent: $accent,
  warn: $warn
);

@each $name, $color in $theme-colors {
  &.mat-#{$name} {
    @include _mat-tab-label-focus($color);
    @include _mat-ink-bar($color);
  }

  &.mat-background-#{$name} {
    @include _mat-tab-label-focus($color);
    @include _mat-tabs-background($color);
 }

 &.mat-#{$name}.mat-background-#{$name} {
  @include _mat-ink-bar($color, default-contrast);
 }
}
```

**Comment by willshowell** [comment]
cc @andrewseguin

**Comment by jelbourn** [comment]
Review on this one might be delayed a bit (Andrew is wrapping up initial data table stuff)

**Comment by willshowell** [comment]
@jelbourn fair, thank you for the update

**Comment by willshowell** [comment]
@andrewseguin done, PTAL

**Comment by kara** [comment]
@willshowell Can you rebase again? Sorry!

**Comment by willshowell** [comment]
@kara done!

**Pull request merged**
