### PR TITLE
fix(tabs): scale the contents of mat-tab-group to the group's height

### LINKED ISSUE #4591: md-tab doen't gives height=100% to give all height of md-tab-group
Hi,

I'm having problems to adjust content of a tab to 100% of height of md-tab-group

For example:

```
<md-tab-group style="background-color: lightblue; height: 100%">// this works all bk is blue
<md-tab label="Info" style="background-color: indianred; height: 100%">//not work
<div style="background-color: yellow; height: 100%"></div>//with % not work, with px works
</md-tab>
</md-tab-group>
```
My problem is that `md-tab-group` expands his `height` to total of `height`. But the atribute `height` of `md-tab` doesn't fit to 100% of `md-tab-group`.

Because of that the content, even if I set the height to 100% it doesn't fit to 100% of `height`

If I set thet `height` attribute of the `<div>` to for example 500px it works correctly

I have this problem since I added `<!doctype html>` to my index.html

Versions: Beta.5
                Angular 4

What would be doing wrong?

### PR DESCRIPTION
**Pull request by CDDelta**
Implements the fix by @RobJacobs to correctly scale the contents of `mat-tab-group` to the group's height.

Fixes #4591

### CODE REVIEW

**Comment by CDDelta** [comment]
cc. @andrewseguin. Do you have time to review this before 6.0?

**Comment by darkbasic** [comment]
Is there any reason why the PR hasn't still been merged after 5 months?

**Comment by andrewseguin** [comment]
My apologies, this slipped by on my radar as I was working on a few other parts of core and Material. The change looks good to me, but I'm going to run it through the internal Google test suite to confirm that it doesn't cause any unexpected changes.

**Comment by CDDelta** [comment]
Damn, I messed up the rebase. Still a noob. I will open another pull request and close this. Sorry!

**Pull request closed without merging**
