### PR TITLE
fix(chips): Update chips in chip list, and add margin to chip input

### LINKED ISSUE #8509: Chip input placeholder issue with async chips update
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Refresh the state (including placeholder) automatically on async chips update.

#### What is the current behavior?
The placeholder remains there if chips are updated async and `floatPlaceholder` is set to `"never"`. (State refreshes and placeholder disappears when I click inside input.)

#### What are the steps to reproduce?
https://plnkr.co/edit/WHW38I60XQkeo6Bl9KA2?p=preview
image

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest on Plunker.

#### Is there anything else we should know?
Maybe related: #8448

### PR DESCRIPTION
**Pull request by tinayuangao**
Fixes #8509 #8505

### CODE REVIEW

**Comment by merobal** [comment]
@tinayuangao Adding stateCheck to ngAfterContentInit not fully solve #8509. In our case we update chips from dialog (where user can select from dozens of filters) and we add the selected filters as chips to the chip input component. Demo for this issue: https://plnkr.co/edit/eGPxQCkLCK7T38GDJOzv?p=preview (add chips via external functionality such as via button click. This is why I suggest ngOnChanges.)

**Comment by tinayuangao** [comment]
@merobal The `stateChange` is inside `chips.changes` so whenever the `@ContentChildren(MatChip)` chip list changes, `stateChange.next()` will be triggered.

Tested with your demo and it works.

**Comment by merobal** [comment]
@tinayuangao then what's different for me? For me, in Chrome, when I click on the button the placeholder remains there. Screenshot:
image

**Comment by merobal** [comment]
@tinayuangao it's still an issue in the final release:
https://youtu.be/-ohHhYxwfD0

**Comment by merobal** [comment]
@tinayuangao do you have any update on this?

**Comment by merobal** [comment]
@tinayuangao do you have any progress on this?

**Pull request merged**
