### PR TITLE
fix(tabs): hidden tabs don't render expansion panels correctly

### PR DESCRIPTION
**Pull request by tiaguinho**
Fix issue https://github.com/angular/material2/issues/5269

### CODE REVIEW

**Comment by tiaguinho** [comment]
I just add the test on the demo app.

**Comment by josephperrott** [comment]
In looking closer at this change, we actually can't do this change as it is a major change to the workings of material tabs.  This change immediately attaches all of the tab bodies to the DOM, which places more items in the DOM that are needed.

**Comment by tiaguinho** [comment]
When I made the change, I see this problem too. This probably will reduce tabs performance because all the bodies are attached to the DOM.
But fixing the bug isn't better than have performance with a bug? 
This can't be a workaround until we find a better solution?

**Comment by josephperrott** [comment]
We determined that it is more valuable to not change the functionality back and forth between the two concepts.  Also in the near future we should be able to land #6832 which also could be used as a workaround.

**Comment by tiaguinho** [comment]
Ok.
Thank you.

**Pull request closed without merging**
