### PR TITLE
"mdMenuTriggerFor" -> "md-menu-trigger-for"

### PR DESCRIPTION
**Pull request by GerrAlt12**
looks like property "mdMenuTriggerFor" should be "md-menu-trigger-for"

### CODE REVIEW

**Comment by GerrAlt12** [comment]
signing completed

**Comment by crisbeto** [comment]
No it shouldn't, all of the Material properties were switched to camelCase for consistency.

**Comment by GerrAlt12** [comment]
but I have error now:
"Can't bind to 'mdMenuTriggerFor' since it isn't a known property of 'button'. ("<md-toolbar [color]="primary">
    <button md-icon-button [ERROR ->][mdMenuTriggerFor]="menu">"

with "md-menu-trigger-for" I have no compilation errors, I do something wrong?

**Comment by crisbeto** [comment]
The renamed properties haven't been released yet. You should use md-menu-trigger-for until the next release.

**Comment by GerrAlt12** [comment]
OK

it is a pity that Marty brought the documentation without the code

**Pull request closed without merging**
