### PR TITLE
docs(table): fix typo in link to cdk-table guide.

### PR DESCRIPTION
**Pull request by nkwood**

### CODE REVIEW

**Comment by jelbourn** [comment]
Ah, I saw #5565 first

**Comment by leocaseiro** [comment]
@nkwood Sorry, I didn't see that =/

**Comment by jelbourn** [comment]
You were first, I just read the PRs from top to bottom.

**Comment by nkwood** [comment]
Ha! No problem. I'm ready to spring into action for the next typo. 😄

**Pull request closed without merging**
