### PR TITLE
chore(slide-toggle): demo for slide-toggle with forms

### LINKED ISSUE #3161: docs: simple example for slide-toggle with ngModel
#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

### PR DESCRIPTION
**Pull request by DevVersion**
* People were confused about the configurable slide-toggle demo using the `[checked]` input binding. There should be an example that demonstrates how to use the slide-toggle with the different Form possibilities. 

Closes #3161

### CODE REVIEW

**Comment by mbritton** [comment]
I am struggling with this. Where is the documentation?????

**Comment by mmalerba** [comment]
@mbritton you can see the example code that was added in this PR, just look at the changed files. It hasn't made it to the docs site yet, but it will be in the examples section of the slide-toggle docs soon: https://material.angular.io/components/slide-toggle/overview

**Comment by mbritton** [comment]
`<mat-slide-toggle [disabled]="false" #mypoliciestoggle class="mpo-slide-toggle" (click)="onMyPoliciesOnlyClick()" [color]="accent"
                      [checked]="isMyPolicies">My Policies Only
    </mat-slide-toggle>`

I have a local boolean that updates based on the value of a subscription to an Observable<boolean>. When I click the toggle the first time, the model is updated and a new value returned. The toggle doesn't reflect this value.

I've had problems with this component for a long time.

**Comment by hughanderson4** [comment]
1. this PR has `md-` prefix instead of `mat-` prefix.

2. When I try to use `[(ngModel)]` with `mat-slide-toggle` I get this error: `No value accessor for form control with unspecified name attribute`.  I rather not assign a name to this item since it's being outputted in a `*ngFor` loop.  Must I really construct a unique name using a loop $index?

**Pull request merged**
