### PR TITLE
test(menu): fix test failures against Angular 4.2

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a couple of menu unit tests that were failing against Angular 4.2.2.

### CODE REVIEW

**Comment by crisbeto** [comment]
This seems to be the only place where it was happening, though. Perhaps we overlooked it?

**Comment by jelbourn** [comment]
I'm starting to think it's a bug because we import `NoopAnimationModule` and Angular's delegation to the animation driver for removal is not removing the element. Stepping through the animation code now.

**Comment by jelbourn** [comment]
I suspect 
https://github.com/angular/angular/blob/6ca46929fa26468f179196979b5f77a48f79991f/packages/animations/browser/src/render/transition_animation_engine.ts#L299-L299

**Comment by alexw10** [comment]
Any update on this / on the path forward?

**Pull request merged**
