### PR TITLE
fix(sidenav): hide drawer shadow in 'side' mode

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Comment by tinayuangao** [comment]
LGTM

**Comment by mmalerba** [comment]
fixes #2674

**Comment by andrewseguin** [comment]
Was this to match a closer spec to material design? I haven't seen an example of a persistent sidenav that doesn't have any depth/border to it. I don't think this looks as nice as before. I think mat-elevation-16 was overkill but I'd recommend putting in at least mat-elevation-2.

**Comment by mmalerba** [comment]
@andrewseguin yes this was to match the spec: https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior no reason you can't just add the elevation class in your app though

**Pull request merged**
