### PR TITLE
style(snackbar): remove border radius from center-aligned positions

### PR DESCRIPTION
**Pull request by willshowell**

### CODE REVIEW

**Comment by willshowell** [comment]
This was to fix a minor nit of mine, but it looks like the spec is inconsistent.

Shows bottom border radius:
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B57Y8yNEHsZPVkRWSkNRLVNzQXc/components-toasts-tabletdesktop2.png

Shows no border radii at all:
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsLVVnZlF4UEtKRU0/components-snackbar-specs-fabtablet-002.webm

@jelbourn feel free to close if not needed.

**Comment by josephperrott** [comment]
I am not sure why the animation they show has no border radius.  However for tablet/desktop the corners are specifically defined: `2dp rounded corner` so I think we will leave it as 2px for tablet/desktop.

The mobile version does not have this, however we do not yet do the mobile styling as we are still pending our `BreakpointObserver`

**Comment by willshowell** [comment]
@josephperrott Yeah I'm certainly in agreement with the borders having a 2px radius. My proposal is specifically about the corners that align with the viewport edge:

snackbar-border-radius

To me, it's mildly annoying, but easy enough to override myself. I would just like to make sure you didn't think I was proposing to remove all the border radii. 😄

**Comment by josephperrott** [comment]
You are correct, I did misunderstand what you were looking to do, sorry about that.  For now we will leave it as is in the library, though I reached out to some people to determine the official guidance.

**Comment by willshowell** [comment]
Thanks!

**Comment by willshowell** [comment]
@josephperrott any response?

**Comment by jelbourn** [comment]
Response from Material UX: they should always have rounded corners, the place where they don't is a mistake.

**Comment by willshowell** [comment]
Bizarre - it seems like a given to me that you'd want alignment against the viewport, but ack 👍

**Pull request closed without merging**
