### PR TITLE
test(slide-togle): add missing e2e tests for slide-toggle component

### LINKED ISSUE #1963: Add e2e tests for slide-toggle
We should have some e2e tests for the slide-toggle component.

### PR DESCRIPTION
**Pull request by Drumarcco**
Add e2e tests for slide-toggle component to verify click changes its checked state only when
the component is enabled.

Closes #1963 

@DevVersion

### CODE REVIEW

**Comment by DevVersion** [comment]
@Drumarcco Actually I started working on those already. So your work now interferes with mine..

**Comment by Drumarcco** [comment]
Oh, that's my bad, I didn't notice it was already assigned @DevVersion, sorry about that :sweat_smile:. 

Are the "good for community contribution" labeled issues the ones I should try to contribute to or should I contribute with others too?

**Comment by DevVersion** [comment]
@Drumarcco No worries. Yeah those should be always good to work on - But it's always good to ask if someone already started working on the specific issue.

I would be happy to close your PR here.

**Comment by Drumarcco** [comment]
@DevVersion Thanks for the feedback, go ahead :+1:

**Pull request closed without merging**
