### PR TITLE
fix(slider): not reacting to directionality changes

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes the slider not updating if its direction is changed dynamically. This is something I came across while testing #6641.

### CODE REVIEW

**Comment by mmalerba** [comment]
I believe @g1shin is working on this in her PR for #6542

**Comment by crisbeto** [comment]
#6542 seems to be related to the focus styles, not the directionality, although the fix should be somewhat similar (adding in a missing `markForCheck` somewhere).

**Comment by mmalerba** [comment]
yeah she's just fixing the various OnPush issues

**Comment by crisbeto** [comment]
Alright, closing in that case.

**Pull request closed without merging**
