### PR TITLE
docs(starting-guide) improve import of hammerjs

### LINKED ISSUE #3061: Possible error in getting started guide
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Documentation at https://github.com/angular/material2/blob/master/guides/getting-started.md#install-angular-cli 
indicates to include 
import 'hammerjs';

#### What is the current behavior?
To avoid warnings, it should be 
import 'hammerjs/hammer';

#### What are the steps to reproduce?
Just follow the getting started guide

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/o077B6uEiiIgkC0S06dd

#### What is the use-case or motivation for changing an existing behavior?
Clean documentation

### PR DESCRIPTION
**Pull request by vitorreis**
Fixes #3061

### CODE REVIEW

**Comment by vitorreis** [comment]
I signed it!

**Comment by crisbeto** [comment]
Could you rename your PR to refer to the getting started guide? Looking at the title, this looked like it removes the warning completely.

**Comment by vitorreis** [comment]
Done @crisbeto

**Comment by DevVersion** [comment]
@vitorreis Why is this necessary? Loaders are actually smart enough to detect that the package from HammerJS redirects to the `hammer.js` file. See for example [this](https://unpkg.com/hammerjs@2.0.8/package.json)

**Comment by vitorreis** [comment]
True @DevVersion, I am closing this pr

**Pull request closed without merging**
