### PR TITLE
refactor: move FocusOriginMonitor into CDK

### PR DESCRIPTION
**Pull request by crisbeto**
Moves the `FocusOriginMonitor` into `@angular/cdk/a11y`, renames it to `FocusMonitor`, deprecates the `StyleModule` and updates all the references.

BREAKING CHANGE: `FocusOriginMonitor` has been renamed to `FocusMonitor`.

### CODE REVIEW

**Comment by mmalerba** [comment]
While we're at it, I'd kind of like to rename it to just `FocusMonitor`. @jelbourn WDYT?

**Comment by jelbourn** [comment]
`FocusMonitor` sounds fine to me

**Comment by crisbeto** [comment]
Done @mmalerba @jelbourn, PTAL.

**Comment by e-cloud** [comment]
@jelbourn you forgot to mention StyleModule is deprecated in release note.

**Pull request merged**
