### PR TITLE
build: switch karma.conf to typescript

### PR DESCRIPTION
**Pull request by crisbeto**
Switches the `karma.conf` to TypeScript.

### CODE REVIEW

**Comment by DevVersion** [comment]
@jelbourn I can't really remember of a strong reason, just that we wanted Karma to start-up faster without using `ts-node` and that we wanted to support launching Karma  in the specific IDEs.

e.g. Webstorm has a pretty nice run configuration that allows easy-debugging of spec files, but won't be able to read a TS karma config.

**Comment by crisbeto** [comment]
Maybe that has changed since the last time this was checked? It seems like Karma itself handles TS properly both through the CLI and the programmatic API.

**Comment by DevVersion** [comment]
The only reason it works right now is that we have registered `ts-node` within the `gulpfile.js` AFAIK. Karma does not have any known support for TypeScript (except for processors)

**Comment by crisbeto** [comment]
I see, I'm not sure why I was under the impression that it was working through the CLI. Do we still want the type safety and sacrifice the Webstorm integration? I can also add a `karma.conf.js` that just registers the config with `ts-node`, similarly to the Gulp config.

**Comment by DevVersion** [comment]
Not sure if we gain a lot from using TypeScript here. The typings for the Karma config do not really account for the various plugins we use. 

I personally don't really think that it would be needed, since plain JavaScript is pretty clean in such cases, but I don't care that much. You decide.

**Comment by jelbourn** [comment]
Yeah, I'd agree that the config file is simple enough that there's not a huge benefit. I haven't used the WebStorm integration in a while, but I'd like to think I _could_ get it working again.

**Comment by crisbeto** [comment]
Closing to avoid issues with IDEs.

**Pull request closed without merging**
