### PR TITLE
docs: edit mdtab position and origin to not be exposed to api docs

### PR DESCRIPTION
**Pull request by zbagley**

### CODE REVIEW

**Comment by julianobrasil** [comment]
@zbagley, you must change this code lines in `tab-group.html` too ([see code in master](https://github.com/angular/material2/blob/374aaffa83b94cd154a6bfcf7391b34c24282d52/src/lib/tabs/tab-group.html#L34-L35))

image

**Comment by zbagley** [comment]
@julianobrasil Missed that HTML before, but updated now. I'm heading out of my office right now, and I didn't update the spec tests. If needed I can update and push a new commit at some point tomorrow.

**Comment by julianobrasil** [comment]
Yeah, the specs have to be updated too (take a look at Travis output).

**Comment by zbagley** [comment]
Not exactly sure why that screenshot test failed. Passed last time and all I changed was the specs. Screenshot failed on unrelated item.

**Comment by julianobrasil** [comment]
I agree... it failed in and unrelated item.

**Comment by jelbourn** [comment]
Closing this since it's become quite stale. Feel free to open a new PR if this is still relevant.

**Pull request closed without merging**
