### PR TITLE
refactor: switch to HttpClient

### PR DESCRIPTION
**Pull request by crisbeto**
Refactors all of the usages of the deprecated `Http` by replacing them with the `HttpClient`.

**Note:** We need to keep `@angular/http` as a dev dependency in order for the prerender CI check to work.

BREAKING CHANGE: Material now requires `@angular/common` instead of `@angular/http` and uses `HttpClient` instead of `Http`.

### CODE REVIEW

**Comment by rafaelss95** [comment]
I think it's already covered by #6454.

**Comment by jelbourn** [comment]
@crisbeto just needs rebase

**Comment by jelbourn** [comment]
Looks like this one needs rebease

**Comment by crisbeto** [comment]
Rebased.

**Comment by mmalerba** [comment]
please rebase

**Comment by crisbeto** [comment]
Rebased.

**Comment by princemaple** [comment]
Will this be merged soon? Was hoping it could make beta 11, well...

**Comment by cyrilletuzi** [comment]
@rafaelss95 thanks for noticing ;)

**Comment by jelbourn** [comment]
Status update: after some _super fun time_ debugging an issue with `HttpClient` and Closure Compiler, we have a fix (https://github.com/angular/angular/pull/19360, plus some internal google stuff), on top of having patches ready for Google apps' tests that depended on the old `MockBackend` done

**Comment by andrewseguin** [comment]
Needs rebase

**Comment by crisbeto** [comment]
Rebased @andrewseguin.

**Comment by andrey-programmist** [comment]
It's need to remove dependencies from **platform-server**
[http](https://github.com/angular/platform-server-builds/blob/master/src/http.d.ts)

**Comment by Splaktar** [comment]
This merge did unfortunately add back `MdIconRegistry` instead of `MatIconRegistry`:  https://github.com/angular/material2/blob/master/src/lib/icon/icon-registry.ts#L491

**Comment by andrewseguin** [comment]
Thanks @Splaktar - made PR in #8940

**Pull request merged**
