### PR TITLE
refactor: move version export to core entry-point

### PR DESCRIPTION
**Pull request by devversion**
* Moves the `VERSION` export to the the `core` secondary entry-point. This ensures that the V8 package schematics don't resolve the `VERSION` symbol to the incorrect `@angular/material/typings` module name.
* Removes the unused and outdated material subpackages test case that has been replaced with a working one.
* Ensures that the V8 material imports rule resolves the symbol from the imported identifier and not from the aliased one (minor cleanup; no effect as we resolve the identifer to the original symbol anyway; just slower)

Related to: https://github.com/angular/material.angular.io/pull/590

### CODE REVIEW

**Comment by jelbourn** [comment]
This just needs a `BREAKING CHANGE` marker in the commit message

**Comment by devversion** [comment]
What is the breaking change? There is no change in public API technically. Or do you just want a general note reflecting what has changed under the hood?

**Comment by jelbourn** [comment]
Nevermind, I forgot that all the core symbols are already re-exported through the root

**Comment by devversion** [comment]
@jelbourn Ready. waited for CI to be green.

**Pull request merged**
