### PR TITLE
refactor(form-field): use color mixin

### PR DESCRIPTION
**Pull request by rafaelss95**
The color attribute for the `form-field` now uses the color mixin as every other component that is themable.

### CODE REVIEW

**Comment by jelbourn** [comment]
@rafaelss95 could you rebase this PR?

**Comment by rafaelss95** [comment]
Done, @jelbourn. Is there a way to _squash_ those "merges"?

**Comment by jelbourn** [comment]
Since this broadens the type rather than restricting it, I'm changing it to patch release
(no Google apps were affected by it)

**Comment by rafaelss95** [comment]
Travis fail seems to be unrelated to this PR.

**Pull request merged**
