### PR TITLE
refactor(schematics): add test cases for cdk ng-update

### PR DESCRIPTION
**Pull request by DevVersion**
* Adds test cases that had to be removed in favor for a quick implementation of CDK ng update. Now both CDK and Material update schematics should be covered.

### CODE REVIEW

**Comment by jelbourn** [comment]
Just needs rebase

**Comment by DevVersion** [comment]
@jelbourn Done.

**Comment by andrewseguin** [comment]
Sorry, needs another rebase

**Comment by DevVersion** [comment]
Done @andrewseguin

**Pull request merged**
