### PR TITLE
Robustness check on requestAnimationFrame

### PR DESCRIPTION
**Pull request by atardadi**

### CODE REVIEW

**Comment by atardadi** [comment]
Found the issue when going through [this](https://mobile.angular.io/guides/app-shell.html) demo

**Comment by atardadi** [comment]
Singed the CLA

**Comment by jelbourn** [comment]
@atardadi DId you run into some issue where this was necessary?

**Comment by atardadi** [comment]
I did a tutorial on angular mobile toolkit and it throws an exception on that line

**Comment by jelbourn** [comment]
We're going to revist this when we tackle support for Angular Univeral; updates will be in #308

**Pull request closed without merging**
