### PR TITLE
feat(md-icon theming): added color attribute to md-icon for icon them…

### PR DESCRIPTION
**Pull request by tdawgy**
Adds theming to md-icon resolving issue #1888

### CODE REVIEW

**Comment by jelbourn** [comment]
@tdawgy you've got some lint errors:
https://travis-ci.org/angular/material2/jobs/176509279#L261

**Comment by tdawgy** [comment]
Sorry about that, should be resolved now.

**Comment by jelbourn** [comment]
LGTM, thanks!

It would also be helpful to file a follow-up PR to update the README

**Comment by tdawgy** [comment]
Why not include the README update in this PR? Just curious :)

**Comment by jelbourn** [comment]
Typically should avoid changes after PR approval.

**Comment by tdawgy** [comment]
Makes sense, thanks

**Pull request merged**
