### PR TITLE
chore: use table examples for demo app

### PR DESCRIPTION
**Pull request by andrewseguin**
Based off #11112

Updates the table page on the demo app to depend more on table examples. Still would like to migrate the remaining ones over

### CODE REVIEW

**Comment by jelbourn** [comment]
@andrewseguin looks like this has real failures on CI

**Comment by andrewseguin** [comment]
Note, not `merge ready` until #11112 is in

**Comment by jelbourn** [comment]
@andrewseguin needs rebase now that the dependency is in

**Comment by andrewseguin** [comment]
Thanks, rebased

**Pull request merged**
