### PR TITLE
Create windows batch file for staging releases

### PR DESCRIPTION
**Pull request by NCC1701M**
Windows user can build material and create a release version.

### CODE REVIEW

**Comment by NCC1701M** [comment]
I signed it!

**Comment by jelbourn** [comment]
@NCC1701M why do you need this?

**Comment by NCC1701M** [comment]
For example as a workaround as long as custom themes are not implemented for everyone who want to try material2 but don't want to use the default theme. And for all who want to compile material2 on a windows machine

**Comment by jelbourn** [comment]
LGTM

Perhaps we could delete this once bash support in Windows 10 makes it to the public release.

**Comment by DevVersion** [comment]
@NCC1701M @jelbourn I'm just a bit wondering. 

Normally in other projects (like Material 1 etc.) there will be no BAT scripts. 

The default developer environment on Windows includes a Bash Terminal, like the Git Bash (MingW) or Cygwin. 

Once we add BAT files to projects, we will have to add BAT files for other scripts as well. (Even) if the script is actually doing the same as the Bash Script (just different syntax).

Just throwing some thoughts here.

**Comment by jelbourn** [comment]
@DevVersion I just don't really care that much about having the extra file. I'm not going to take extra steps to maintain it, though.

**Comment by NCC1701M** [comment]
@DevVersion @jelbourn  As I mentioned above it's a workaround as long as theming isn't working. As far as I'm concerned the file can be deleted after implementing theming.

@jelbourn That's ok if there is any problem with the file just contact me. I'll take care.

@DevVersion I am a windows developer and I've never needed a Bash Terminal ;-)

**Comment by DevVersion** [comment]
I'm fine with it. I just wanted to get the initial thoughts here.

It would be probably better to just make it a node file. This would work on all environments.

**Pull request merged**
