### PR TITLE
test(): Remove `main` method wrapper from all test files

### LINKED ISSUE #480: Remove `main` method wrapper from all test files.
All of the test files are current wrapped in a `main` method which is no longer necessary. The `describe` block can simply exist on the top level.

### PR DESCRIPTION
**Pull request by trik**
Closes #480

### CODE REVIEW

**Comment by DevVersion** [comment]
You should also remove the entry-point of the tests in the shim file.

- https://github.com/angular/material2/blob/master/test/karma-test-shim.js#L50

**Comment by trik** [comment]
removed the check in the shim file. the number of tests executed remains the same

Chrome 50.0.2661 (Mac OS X 10.11.4): Executed 187 of 187 SUCCESS (5.439 secs / 5.395 secs)

**Comment by jelbourn** [comment]
LGTM

**Comment by jelbourn** [comment]
Thanks!

**Pull request merged**
