### PR TITLE
Fix: removed un-used "this" from html bindings

### PR DESCRIPTION
**Pull request by dharmeshpipariya**

### CODE REVIEW

**Comment by andrewseguin** [comment]
Please rebase

**Comment by dharmeshpipariya** [comment]
@andrewseguin i have rebased PR with master.

**Comment by mmalerba** [comment]
@dharmeshpipariya can you squash this into a single commit? the script we use to merge into google's codebase is unhappy about the merge commits. sorry for the inconvenience...

**Comment by dharmeshpipariya** [comment]
@mmalerba closing this, will send a new PR

**Pull request closed without merging**
