### PR TITLE
chore: add firebase.json for testing

### PR DESCRIPTION
**Pull request by jelbourn**
R: @kara 

FYI: @hansl @robertmesserle 

This gives us an quick-and-easy way to push our local changes to a publicly reachable place. You just run `firebase deploy` from your project root and it will push your most recent build up to https://material2-test.firebaseapp.com.

While it's possible we collide in doing this, it's unlikely with just the few of us doing it.

### CODE REVIEW

**Comment by hansl** [comment]
LGTM.

**Comment by hansl** [comment]
What kind of authentication does `firebase` uses?

**Comment by jelbourn** [comment]
Add devDependency and npm script

**Comment by jelbourn** [comment]
@hansl Google auth

**Pull request merged**
