### PR TITLE
refactor: replace disabled getters/setters with mixin

### PR DESCRIPTION
**Pull request by DevVersion**
* Replaces all remaining `disabled` getters and setters with the new disabled mixin
* Some disabled getters and setters have been skipped because those include extra logic in their setters/getters.

### CODE REVIEW

**Comment by crisbeto** [comment]
FWIW, the button toggle group classes are consolidated into one in https://github.com/angular/material2/pull/2773.

**Comment by DevVersion** [comment]
@crisbeto Nice. I just added it as a note on my PR. Going to remove it now.

**Comment by jelbourn** [comment]
@DevVersion so are you going to remove the changes to button-toggle?

**Comment by DevVersion** [comment]
@jelbourn #2773 doesn’t really relate to the mixin here, it doesn‘t switch to to the disabled mixin (probably not present at this time)

I can remove the button-toggle change to avoid merge conflicts but it looks like it would be a easy conflict to solve.

**Pull request merged**
