### PR TITLE
fix(progress-circle): Fix type for timer

### PR DESCRIPTION
**Pull request by kacepe**
I fixed type error
`Type 'Timer' is not assignable to type 'number'`

Now `_interdeterminateInterval` is type of `NodeJS.Timer`

### CODE REVIEW

**Comment by crisbeto** [comment]
This won't work in the browser.

**Comment by kacepe** [comment]
It's working for me.

**Comment by DevVersion** [comment]
It will still work in the browser because the types don't matter after compilation anymore.

Anyways I think it's not valid to use a type from the `NodeJS` namespace here.

**Comment by jelbourn** [comment]
@kacepe The correct type is actually number. It sounds like you're using the typings for NodeJS in your project instead of the typings for the browser. You want to use lib.es6.d.ts when building material (since it is only meant to run on a browser platform).

The other changes in this PR will also break our build (we do not use angular-cli).

**Pull request closed without merging**
