### PR TITLE
chore(table): remove data prefix

### PR DESCRIPTION
**Pull request by andrewseguin**
Renamed the data-table to just table. Moved to CDK. Removed jasmine custom matchers that are in lib/core of @angular/material

### CODE REVIEW

**Comment by jelbourn** [comment]
Caretaker note: this will require updating build rules

**Comment by tinayuangao** [comment]
@andrewseguin Please rebase. Thanks

**Comment by andrewseguin** [comment]
Rebased

**Comment by tinayuangao** [comment]
@andrewseguin Please fix the tests

**Comment by andrewseguin** [comment]
Rebased, should be good

**Pull request merged**
