### PR TITLE
bug(md-select): change the arrow position to absolute

### LINKED ISSUE #3112: bug(md-select) - not rendering correctly inside a flex layout (pure css) when having ngModel
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
When inside a flex layout (pure css), the md-select must behave consistently, independent if it has a ngModel or not.

#### What is the current behavior?
When the md-select has a ngModel, and it's width is different from the default at page load (inside of a flex layout), the component does not fit inside the container.

This plunker demostrate this behavior:
[Plunker](http://plnkr.co/edit/O1V6N8jCyWpHdu1VTB12?p=preview)

#### What is the use-case or motivation for changing an existing behavior?
We need to display our pages in a responsive layout and are using just pure css flex layout while we wait for [Angular Flex Layout](https://github.com/angular/flex-layout) to became more stable.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-beta.1
Firefox: 51.0.1 (64-bit)
Chromium: 53.0.2785.143
Chrome: 56.0.2924.87

### PR DESCRIPTION
**Pull request by jefersonestevo**
Fixes #3112

Closing #3242 due to merge conflicts

### CODE REVIEW

**Comment by kara** [comment]
This change looks like it breaks the placeholder positioning. It no longer cuts off the overflow for a long placeholder.

**Comment by mmalerba** [comment]
@kara Ok, reverting

**Comment by kara** [comment]
@jefersonestevo Do you mind looking into the long placeholder issue? Probably just needs a minor tweak. If you can fix that, we can make sure this gets re-merged ASAP.

**Comment by jefersonestevo** [comment]
@kara I've reviewed the code and find that the problem is on the programmatic calculation of the placeholder width. I've commited the correction on my branch, but I thing that, as this PR has already been merged, it'll no longer get any commit from my original branch. Should I open a new PR?

**Comment by mmalerba** [comment]
@jefersonestevo yeah you can just open a new one, sorry for the hassle

**Comment by jefersonestevo** [comment]
@mmalerba @kara PR #3602 created. If there are anything else that needs to change just let me know

**Pull request merged**
