### PR TITLE
fix(select): Fixes width-issue of select option panel in IE

### LINKED ISSUE #11609: IE11: Width of select Panel is too low
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The Width of the select-panel should be as large as in other Browsers, so that especially longer options can be read.

#### What is the current behavior?
The select panel is way shorter, so that longer options are truncated early. On opening the Select Panel you can even see, that the width gets adjusted from a wider width to a lower width in a split of a second.
In IE11:
grafik
In Chrome 67:
grafik

Another point is the invisible part of the select-panel, the "cdk-overlay-pane", it's width is now much wider, so that you cannot close the panel by clicking next to it, because there is no backdrop yet
grafik

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-mm2na2?file=app/app.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
The stackblitz is build using Angular 6.0.x and Material 6.2.0. But at least lower 6.x.x Versions of Material are affected too.

### PR DESCRIPTION
**Pull request by macjohnny**
Fixes the select options panel width not matching the select width in IE11

Fixes #11609.

### CODE REVIEW

**Comment by macjohnny** [comment]
@crisbeto 
> It doesn't look like this solves it completely. The animation still jumps on IE:

You are right, however, I think this is a separate issue, although related: https://github.com/angular/material2/issues/11642

**Comment by crisbeto** [comment]
If you know how to fix it, it would be good to fix both of them, otherwise it can be addressed later. Also is there a way to work around having to add an extra wrapper around the select panel?

**Comment by macjohnny** [comment]
@crisbeto 
> If you know how to fix it, it would be good to fix both of them, otherwise it can be addressed later.

ok, I will see if I find a solution for that, too.

> Also is there a way to work around having to add an extra wrapper around the select panel?

So far, I didn't find a way without adding additional markup (apart from using `display: block` instead of `display: flex` on the `.mat-overlay-pane`). However, I think it is ok to have the `.mat-select-panel-wrap` with `flex-basis: 100%;`, since this works the same way as a properly expanding `div` container, setting the stage for the children.

Or do you see any other solution? Unfortunately, it has alway been a pain using `display:flex` in IE...

**Comment by macjohnny** [comment]
concerning https://github.com/angular/material2/issues/11642:

the reason for the remaining jump of 32px at the end of the animation is the animation transition from `min-width: 100%` ([src/lib/select/select-animations.ts#L43](https://github.com/angular/material2/blob/48dda505f78ba82be385b025c6c5eb5ff51e8a84/src/lib/select/select-animations.ts#L43)) to `min-width: calc(100% + 32px)` ([src/lib/select/select-animations.ts#L48](https://github.com/angular/material2/blob/48dda505f78ba82be385b025c6c5eb5ff51e8a84/src/lib/select/select-animations.ts#L48))

this also happens when starting with an initial state of `min-width: calc(100%)`

it seems that this is rather a bug in the angular animations itself, since e.g. `web-animations-js` can handle the transition from `min-width: 100%` to `min-width: calc(100% + 32px)` correctly, see this [codepen example](https://codepen.io/macjohnny-zh/pen/gKGEWb), which works correctly in IE11.

I filed the following bug report: https://github.com/angular/angular/issues/24545

Here is an example using Angular animations to animate the transition from `min-width: 100%` to `min-width: calc(100% + 32px)`: [https://stackblitz.com/edit/angular-gitter-v3xmvv](https://stackblitz.com/edit/angular-gitter-v3xmvv?file=app%2Fapp.component.ts)
It works correctly in Chrome, but it does not work in IE, while animating from e.g. `min-width: 100%` to `min-width: 110%` works in both, Chrome and IE.
Nevertheless, animating from `min-width: 100%` to `min-width: calc(110%)` also fails in IE.

Using CSS-animation does not work either (it works in chrome, however): [https://codepen.io/macjohnny-zh/pen/RJLOWG](https://codepen.io/macjohnny-zh/pen/RJLOWG)

In order to fix https://github.com/angular/material2/issues/11642, I see the following options:

1.) ignore the "little" jump for now, as this PR already reduced the jump in https://github.com/angular/material2/issues/11642 from "large" to "small", while still keeping the issue open to fix the little jump later
2.) wait for a fix of https://github.com/angular/material2/issues/11642
3.) 

@crisbeto how do you want to proceed? I suggest to get this PR ready to be merged and fix the little jump of https://github.com/angular/material2/issues/11642 in a separate PR
I also verified in IE that the test cases I added fail without the fix, and run successfully with the fix.

**Comment by macjohnny** [comment]
@crisbeto thanks for reviewing the PR.
I also tried an alternative way of fixing the width-issue by setting `flex-direction: column` to the `.mat-overlay-pane` element.
This does not change the correct behavior of Chrome:
bildschirmfoto 2018-06-17 um 13 53 19

However, IE would still get it wrong, now the panel being too large because the `max-width: 280px` of `.mat-select-panel` is ignored:
bildschirmfoto 2018-06-17 um 13 52 56

Hence I think the solution of having a `.mat-select-panel-wrap` with `flex-basis: 100%;` fixes the problem properly, so this PR should be good to go.

**Comment by yogeshgadge** [comment]
Those waiting https://github.com/angular/material2/issues/11609#issuecomment-400439149

**Comment by macjohnny** [comment]
@tinayuangao @crisbeto any idea why this PR didn't make it into the `6.3.1` release? is there anything else I need to do?

**Comment by crisbeto** [comment]
The caretaker just hasn't gotten to it yet.

**Comment by macjohnny** [comment]
@crisbeto @josephperrott I rebased my branch on the current master and resolved the conflicts.
Could you please have a look at this PR again? The issue #11609 is still present in the current master. It would be great if this change would make it into `7.0.0`

**Comment by vivian-hu** [comment]
In the effort of trying to run it through the tests of Google internal projects. I found this change made the option panel disappears much faster than before (if you slow the animation, you can see it clearly). It somehow changed the animation behavior and some tests seem very sensitive about the timing.
@macjohnny, can you take a look?

**Comment by macjohnny** [comment]
@vivian-hu I will try to investigate the animation duration

**Comment by macjohnny** [comment]
@vivian-hu I found that the panel leave animation was not rendered due to https://github.com/angular/angular/issues/23302
I added https://github.com/angular/material2/pull/11801/commits/2f6633c426295fd47038249768e1c1122b074dc8#diff-06ebba94235af50e354ccf6fce620251R35 to fix this. Now the animation seems to work correctly again.
@crisbeto could you reconsider a review?

**Comment by macjohnny** [comment]
@vivian-hu could you please have a look at this PR again? it should work correctly and resolve the issue.

**Comment by macjohnny** [comment]
@crisbeto @vivian-hu I updated the PR with the fix suggested by @striky1 in https://github.com/angular/material2/issues/11609#issuecomment-440706201, which does not involve markup changes but only the following additional css property:
```css
.mat-select-panel {
  flex: 1 0 auto;
}
```

So now this PR should fix the issue with minimal changes, while it does not affect the appearance in e.g. Google Chrome. I also tested various widths of the panel and it seems alright, so this PR should be good to go.

I hope this can get merged soon, as this issue has been around for quite a while.

**Comment by macjohnny** [comment]
@josephperrott what can I do about a failing `branch-manager` status?

**Comment by macjohnny** [comment]
@jelbourn the e2e tests ran successfully on my local machine. any way to trigger running them again on CI?

**Comment by macjohnny** [comment]
@crisbeto @vivian-hu @josephperrott any chance to get this change merged? it is small, fixes the still present IE11 issue with mat-select, is updated with the latest master, and passes all checks.

**Comment by macjohnny** [comment]
According to https://github.com/angular/material2/issues/11609#issuecomment-454724013 of @evoltafreak, the css-only solution fails in IE if the options are larger than the trigger width. So I reverted this branch to the markup-solution that (as far as I have tested it) is a working solution.

I saved the css-only solution as a separate branch: 
https://github.com/macjohnny/material2/tree/bugfix/11609-select-ie-width-css-only

**Comment by macjohnny** [comment]
@vivian-hu could you please have a look at this PR again?

**Pull request merged**
