### PR TITLE
feat: rename cdk/keyboard -> keycodes & cdk/observe-content -> observers

### PR DESCRIPTION
**Pull request by jelbourn**

### CODE REVIEW

**Comment by tinayuangao** [comment]
@jelbourn please rebase. Thanks!

**Comment by jelbourn** [comment]
@tinayuangao rebased

**Comment by mmalerba** [comment]
please rebase

**Comment by jelbourn** [comment]
@mmalerba Rebased

**Comment by mmalerba** [comment]
needs rebase

**Comment by jelbourn** [comment]
@mmalerba rebased

**Pull request merged**
