### PR TITLE
Fix(icon): add asynchronous support for adding icons to registry (#3304)

### PR DESCRIPTION
**Pull request by padraig-meaney**
Change the icon-registry to provide a method of subscribing for icons. Allow icons to subscribe for an icon being added to registry asynchronously.

### CODE REVIEW

**Comment by padraig-meaney** [comment]
I guess the most obvious use case is that a user may want to have icons defined in a template that are loaded asynchronously at run time. I guess there's nothing stopping a user having something like *ngIf="iconsloaded" or something like that in their template. Tbh, I pushed this as a fix specifically for #3304 as it was tagged as a good issue for beginners.

**Comment by jelbourn** [comment]
Looking at that issue in more depth now, I'm not sure we should change the current behavior. My concern is: what would be a sensible thing to show when the icon isn't loaded yet? I don't think there's a clear expectation of what would happen if you don't register the icon first.

**Comment by padraig-meaney** [comment]
Hmm, I agree actually. Thinking about it more, I know that font awesome will load in a question mark icon instead of the requested icon if it does not exist, to make it obvious. Not sure if that’s what you’d adopt here, but the way I see it there’s kind of 2 questions: should you log (error/warning?) something to the console, and what (if anything) is rendered on screen.

**Comment by jelbourn** [comment]
Yeah, exactly. It makes it most simple for us to say that you should always register icons before they're used, and we avoid another vector for [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)

**Comment by jelbourn** [comment]
Closing since it seems we're agreed on keeping the current behavior.

**Pull request closed without merging**
