### PR TITLE
chore(ci): block import of entire rxjs library

### PR DESCRIPTION
**Pull request by jelbourn**
R: @hansl @kara  

Thanks to @DevVersion for making me realize we need a check for this.

### CODE REVIEW

**Comment by hansl** [comment]
Can you elaborate? Is it because you want tree shaking?

**Comment by jelbourn** [comment]
@hansl Effectively; all of the imports for rxjs should be for the specific parts you want. If you do `rxjs/Rx`, it brings in the entire library. See `icon.ts`, for example, which does:
```ts
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/forkJoin';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/finally';
import 'rxjs/add/operator/catch';
```

See #431

**Comment by hansl** [comment]
LGTM

**Comment by hansl** [comment]
Thank you for context.

**Pull request merged**
