### PR TITLE
fix(button-toggle): toggle group should not emit an initial change event.

### PR DESCRIPTION
**Pull request by DevVersion**
This is the addition of https://github.com/angular/material2/commit/23a61ab8687d5e4f962c39423ed095959d2da82c, which was only taking care of the `ButtonToggle` itself, and not of the group.

Since the `md-button-toggle-group` does not contain any underlaying input element, and we can't use the `emit event if native input does`  approach, we need to wait for the component view to be ready.

References #1125

### CODE REVIEW

**Comment by colinfang** [comment]
Just wondering, can we put `this._isInitialized = true` in `ngOnInit`? As the property binding are finished before entering `ngOnInit`.

**Comment by DevVersion** [comment]
@colinfang Yeah that works too. I do not recall why we started using the `ngAfterViewInit` hook instead.

**Comment by jelbourn** [comment]
@DevVersion @colinfang Using `ngOnInit` does not work because the order of initialization for directives on the same element is not defined. As such, an `ngModel` on the element may initialize *after* the `ngOnInit` of the component itself.

**Comment by DevVersion** [comment]
@jelbourn Sounds reasonable. Reverted my commit about the `ngOnInit`

**Comment by jelbourn** [comment]
LGTM

**Comment by colinfang** [comment]
@jelbourn  Sorry I don't quite follow up what you mean, I have never made a `ngModel` for a custom component before. Could you please elaborate a little bit more?

Are you saying in 

     <my-component  [ngModel]="abc" ></my-component>

If `ngModel` is mapped to a property say  `Output() myInput`, in `MyComponent.ngOnInit` `myInput` is not defined?

**Comment by jelbourn** [comment]
@colinfang when you have an `ngModel`, _it_ can be responsible for initializing the component, so you want to set `isInitialized = true` _after_ `ngModel` has run, which can be after the component's `onInit`.

**Pull request merged**
