### PR TITLE
chore: bump to angular 4 final

### PR DESCRIPTION
**Pull request by crisbeto**
Bumps the version to Angular 4 final. The release is pretty safe and doesn't need any code changes.

### CODE REVIEW

**Comment by paulwalker** [comment]
Does the @angular/material version needs to be bumped and released as well?

**Comment by jelbourn** [comment]
We're working on cutting a release as soon as possible.

**Comment by basst314** [comment]
Hi @jelbourn, is this a matter of hours/days or weeks?
Just that we know what to expect.
thanks!

**Comment by jelbourn** [comment]
Hopefully just a few days- we've done some work to update our package structure to match `angular/angular`, but we're still tuning it so that it will better support tree-shaking as it exists in Webpack.

**Comment by JordyBaylac** [comment]
Hi @jelbourn I came across the [UNMET PEER DEPENDENCY at #1512](https://github.com/angular/material2/issues/1512) and I would like to know if there any advice, maybe use angular 2.0 instead of 4.0? or should I wait the next release?

PS: Keep doing great!

**Pull request merged**
