### PR TITLE
feat(input): add `md-focused` class to `md-input` element

### PR DESCRIPTION
**Pull request by fxck**
Fixes https://github.com/angular/material2/issues/1135

### CODE REVIEW

**Comment by fxck** [comment]
fails because of timeouts

**Comment by jelbourn** [comment]
Not sure if I want to add this vs.:
```
<md-input #firstName [class.my-custom-focus]="firstName.focused">
```

@hansl thoughts?

**Comment by fxck** [comment]
Just noticed there's a second PR as well https://github.com/angular/material2/pull/1337 with the difference that mine puts the class directly on the host element, which I think is more desirable.

**Comment by hansl** [comment]
There's a completely fine solution outlined by @jelbourn above and I think the issue should be marked as Intended Behaviour. We don't want to go into making a bunch of classes that can be styled by customers, since they can set the classes they want.

**Pull request closed without merging**
