### PR TITLE
refactor(expansion panel): fix spell check on some words 

### PR DESCRIPTION
**Pull request by rafaelss95**
The main purpose of this PR was to simply fix the typos:

- MdAccordianChild -> MdAccordionChild
- CdkAccordonItem -> CdkAccordionItem

But I went deep and fix some styles and minor mistakes.

### CODE REVIEW

**Comment by willshowell** [comment]
@rafaelss95 any reason you closed it? I was going to suggest switching `pallete` to `palette` in pseudo-checkbox-theme. It's been annoying me but I haven't gotten around to opening a PR.

**Comment by rafaelss95** [comment]
@willshowell My fork wasn't updated and I messed everything up trying to rebase :(  I'm opening a new one in a few minutes.

**Comment by rafaelss95** [comment]
Done in #5658. About the checkbox-theme I'm going to open a new PR since it's unrelated to expansion-panel, can be?

**Comment by willshowell** [comment]
Oh right, didn't realize those were all specifically expansion-panel changes

**Pull request closed without merging**
