### PR TITLE
fix(autocomplete-demo): reactiveStates length

### PR DESCRIPTION
**Pull request by gozeon**

### CODE REVIEW

**Comment by gozeon** [comment]
@crisbeto CLA verification is successful, what next do, resubmit the pull request?

**Comment by gozeon** [comment]
Need a second CLA verification ？

**Comment by jelbourn** [comment]
@gozeon your PR needs to be rebased on master

**Comment by gozeon** [comment]
I am an entry-level programmer, please forgive me

**Comment by mmalerba** [comment]
@gozeon seems like there was a bad rebase, do you want to try to fix or just open a new PR?

**Pull request closed without merging**
