### PR TITLE
style(checkbox,chips,tabs): remove hardcoded hues

### LINKED ISSUE #3813: Inconsistent coloring for some components when not using 500 colors
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When handing a non-500 color into the mat-palettes, primary and warn (not accent) components should be rendered with this color, not the corresponding 500 color of the same palette

`$primary: mat-palette($mat-blue, 800, 200, 900);`
--> Should take blue-800, not blue-500

#### What is the current behavior?
Some components always use 500 colors
This applies to the following components when marked as "primary" or "warn":
Checkbox, Chip, Tab, Slider

#### What are the steps to reproduce?
Define a palette with a non-500 color as primary color

#### What is the use-case or motivation for changing an existing behavior?
Consistent coloring behaviour

#### Which versions of Angular, Material, OS, browsers are affected?
angular-material 2.0.0-beta.2
angular 4.0.0

probably all browsers (tested in chrome, firefox, safari)

### PR DESCRIPTION
**Pull request by willshowell**
Fixes #3813

### CODE REVIEW

**Comment by jelbourn** [comment]
@willshowell just needs rebase

**Comment by willshowell** [comment]
@jelbourn done

**Comment by willshowell** [comment]
@jelbourn I just came across the specs for checkboxes and I see that the hues are actually defined to be 500. Should that portion of this PR be reverted or should that be interpreted as to mean the "default hue"?

> **Light**
>
>On: Swatch 500, Opacity 100%
Off: #000000, Opacity 54%
Disabled: #000000, Opacity 26%

> **Dark**
>
>On: Swatch 500, Opacity 100%
Off: #FFFFFF, Opacity 70%
Disabled: #FFFFFF, Opacity 30%

**Comment by jelbourn** [comment]
I'm interpreting it as _intending_ the default hue.

**Pull request merged**
