### PR TITLE
fix(input): remove md-input and md-textarea in favor of md-input-container

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Comment by jelbourn** [comment]
LGTM

**Comment by mmalerba** [comment]
fixes #2217

**Comment by xmeng1** [comment]
I think the npm for input should be updated, or it will confuse the users. 
https://www.npmjs.com/package/@angular2-material/input

**Comment by mmalerba** [comment]
@xmeng1 I think that's an outdated one, the latest is here: https://www.npmjs.com/package/@angular/material

**Pull request merged**
