### PR TITLE
chore: allow for scss imports from node_modules

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Comment by DevVersion** [comment]
Should we consider adding the `include_paths` to the Bazel rules? https://github.com/bazelbuild/rules_sass

<sub>I know that will involve a lot of work, so just asking 😄</sub>

**Comment by jelbourn** [comment]
The rules already support it:
https://github.com/bazelbuild/rules_sass/blob/master/sass/sass.bzl#L172

**Comment by DevVersion** [comment]
Yeah, but adding them to every `sass_binary` rule could take a while. That's what I meant.

**Comment by jelbourn** [comment]
Ah, yeah. If we wanted to add them everywhere we'd want to make a wrapper for `sass_binary` and use that everywhere

**Pull request merged**
