### PR TITLE
fix: remove duplicated typing. TS stdlib provides enough for e2e tests

### PR DESCRIPTION
**Pull request by hansl**

### CODE REVIEW

**Comment by DevVersion** [comment]
@hansl As seen in #631, can we not use the typings manager here and remove the static typings?

**Comment by hansl** [comment]
We'll just skip typings and go directly to `@types` when TS 2.0 is released.

**Comment by hansl** [comment]
R: @jelbourn

**Comment by jelbourn** [comment]
LGTM

**Pull request merged**
