### PR TITLE
fix(e2e): Use current directory so e2e test won't complain about directory not exists

### PR DESCRIPTION
**Pull request by tinayuangao**
R: @jelbourn

### CODE REVIEW

**Comment by DevVersion** [comment]
Should we add this to the `.gitignore`?

**Comment by jelbourn** [comment]
Yeah, the directory should be marked as ignored.

**Comment by crisbeto** [comment]
Also shouldn't we disable screenshots when developing locally? I feel like this would stack up a lot.

**Comment by jelbourn** [comment]
@tinayuangao that's another good point- @DevVersion @crisbeto is there an easy way for the screenshot utility to know if it's local? I'd assume there's an environment variable we can check.

**Comment by tinayuangao** [comment]
Use process.env['TRAVIS'] to check whether it's local. Please take another look. Thanks!

**Comment by DevVersion** [comment]
Just one question, how can we take a look at those screenshots on the CI?

**Comment by tinayuangao** [comment]
> Just one question, how can we take a look at those screenshots on the CI?

Currently there's no way to take a look. We will upload the images, compare them and generate a report later.

**Comment by DevVersion** [comment]
@tinayuangao Cool. I have some nice ideas about the viewing those reports since we also have data about the payload size etc.

**Comment by jelbourn** [comment]
LGTM

**Pull request merged**
