### PR TITLE
feat(toolbar): add elevation styling

### PR DESCRIPTION
**Pull request by code-tree**
Elevation styling appears to have been implemented in most components, but toolbar was missed. This adds it for toolbar.

### CODE REVIEW

**Comment by code-tree** [comment]
I think this probably needs a `z-index`, but not sure what rules this project applies to setting that number.

**Comment by code-tree** [comment]
Also, I think tabs' `z-index` will need to be raised so that the toolbar's shadow doesn't appear when placed above tabs.

image

**Comment by DevVersion** [comment]
I don't think it would be necessary to add the elevation to the `md-toolbar`. 

To be more flexible the developers should just apply the given `md-elevation-z4` class on the toolbar.

Not sure we discussed this already when implementing the toolbar @jelbourn ?

**Comment by jelbourn** [comment]
Agreed with @DevVersion, I would rather compose the re-usable elevation classes (e.g., `.md-elevation-z4`) and toolbar rather than baking it in.

**Comment by code-tree** [comment]
Oh good, I didn't know those elevation classes existed.

The main motivation to me is that the toolbar is barely visible without elevation, when it is plain without primary or accent theme. Dark theme is ok, but light theme it is hard to recognise it from the background.

Maybe an example of using that class should be added to the toolbar readme?

**Comment by cedvdb** [comment]
@jelbourn How do you use those elevation classes ?

```
<md-toolbar color="primary" class="md-elevation-z4">
  <close-icon-app (click)="menuOpened =  !menuOpened" [open]="menuOpened">
  </close-icon-app>
</md-toolbar>
```

**Comment by ghd8** [comment]
@cedvdb  - try "mat-elevation-z4"

**Pull request closed without merging**
