### PR TITLE
build: enable ci testing of schematics

### PR DESCRIPTION
**Pull request by DevVersion**

### CODE REVIEW

**Comment by DevVersion** [comment]
Actually we cannot run tests for the schematics right now. Since we parse the TypeScript files in the schematics using TypeScript 3.0, we cannot just pass the parsed AST to the `@schematics/angular` that uses a different TS version with different `SyntaxKind` mappings.

**Comment by DevVersion** [comment]
Locally, I'm currently just manually installing similar TypeScript versions, so I can run the tests. It would be good if `@schematics/angular` somehow defines TypeScript as a peer dependency.

**Comment by jelbourn** [comment]
@DevVersion file an issue on the cli repo?

**Comment by DevVersion** [comment]
@jelbourn Not sure. I kind of also understand why it has been made a dependency. It would be weird if the actual `CLI` needs to provide an instance of `typescript` that is transitively being used.

There was already some ongoing discussion about it in the tools-CLI channel on Slack. I think the best for us would be to just conditionally load TypeScript from `@schematics/angular/node_modules/typescript` and fall back to `typescript`.

**Pull request closed without merging**
