### PR TITLE
chore(dev-app): add lazy loading

### PR DESCRIPTION
**Pull request by mmalerba**
demo: https://mmalerba-demo1.firebaseapp.com/

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Getting a `StaticInjectorError(MainModule)[SnackBarDemo -> Dir]`  when navigating: landing -> card -> snackbar

**Comment by devversion** [comment]
I got the same today when I wanted to switch the dev-app to Bazel with AOT compilation. Even though it didn't use lazy-loading, I hit the same issue. That's pretty weird.

**Comment by mmalerba** [comment]
I probably missed a module dependency in https://github.com/angular/material2/pull/15498, I'll add the fix to this PR

**Comment by mmalerba** [comment]
It looks like the issue was due to the router-outlet being outside the tree where the `Dir` was provided. I also can't simply move the `Dir` up a component because that would cause the dev-app chrome to switch into RTL too. To solve it I wound up creating a custom root `Directionality` that allows its direction to be set

**Pull request merged**
