### PR TITLE
chore(): remove triple-equals lint rule & make some lint fixes to karma config.

### PR DESCRIPTION
**Pull request by jelbourn**
R: @hansl

### CODE REVIEW

**Comment by hansl** [comment]
Lgtm

**Comment by alexw10** [comment]
What was the reasoning for removing triple-equals?

**Comment by alexw10** [comment]
@jelbourn Any insight on this?

**Comment by jelbourn** [comment]
We turned it off because sometimes we wanted the behavior of `==`. Mostly commonly it's for `== null`.

**Pull request merged**
