### PR TITLE
fix(*): Close #2635 - broken link in getting-started guide

### LINKED ISSUE #2635: broken link to theming guide
#### Bug, feature request, or proposal:
On the getting-started page, the link to the theming guide is broken

#### What is the expected behavior?
that the link would take one to https://material.angular.io/guide/theming

#### What is the current behavior?
it goes to a blank page

#### What are the steps to reproduce?

go to https://material.angular.io/guide/getting-started
click the link at 'See the theming guide for instructions.'

#### What is the use-case or motivation for changing an existing behavior?
when developers use this documentation, they should be able to see how to include core themes and styles

### PR DESCRIPTION
**Pull request by codef0rmer**
I referred links in `theming.md` for the same.

### CODE REVIEW

**Comment by DevVersion** [comment]
This should have been already fixed with SHA https://github.com/angular/material2/commit/60622a590fd4371ad3f876caeb44234bbb075d1d. The docs just haven't been updated yet. 
cc. @jelbourn

**Comment by codef0rmer** [comment]
@DevVersion Are you sure that commit fixes the issue? Because I modified the link manually on the public docs to verify with no luck. Otherwise, @jelbourn Pls close it.

P.S. Damn, I just forgot to check open PRs before creating this one.

**Comment by DevVersion** [comment]
@codef0rmer I see what you mean. Let's wait for @jelbourn's feedback. Not sure whether the links will be mapped somewhere in the documentation.

**Comment by jelbourn** [comment]
The right solution here is a docs processing step that concerts github links to docs-site links. Until we have that, the docs-site should probably avoid linking back to github (since the information will always be for head)

**Comment by jelbourn** [comment]
I think this should be resolved now.

**Pull request closed without merging**
