### PR TITLE
fix(expansion): MatExpansionHeader transition animations

### PR DESCRIPTION
**Pull request by chriskrolak**
See issue #11990 for rationale.

No tests included - I would greatly appreciate help on how to write a unit test for this, since I can only reproduce the bug as a combination of many components.

### CODE REVIEW

**Comment by josephperrott** [comment]
@chriskrolak Can you explain a bit about how this change addresses #11990?  I am not quite following.

**Comment by chriskrolak** [comment]
Honestly I also have no idea how it works; I copied it from a solution somewhere online that I can't find anymore. It does fix the issue though (tested locally).

**Comment by josephperrott** [comment]
For reference purposes https://github.com/angular/angular/issues/18847 looks to be the issue tracking this in angular/angular

**Comment by josephperrott** [comment]
After giving it another pass, I realized the reason that this change actually ends up being a breaking change for the current way things work.  With this change, any expansion panel that starts as expanded would animate to its initial size instead of appearing immediately at the correct size.

**Comment by josephperrott** [comment]
CLA fixed since it was bad from my lint fix commit.

**Pull request merged**
