### PR TITLE
feat(date-picker): Basic date picker

### PR DESCRIPTION
**Pull request by Frly**

### CODE REVIEW

**Comment by jelbourn** [comment]
@Frly the first step on a large contribution like this is to chat with us on the relevant issue (#675). Before going down the road of implementation, we'd need to have a solid plan for everything I mentioned in #1746

For the datepicker specifically, there is a revision of the spec in the works. We don't want to build/maintain a picker before that revision is ready. 

I encourage you to release your datepicker as a standalone package- I know there any many people that would like to use it!

**Comment by Frly** [comment]
@jelbourn The service overlay is working, I have not uploaded completely, it is missing:
* Support for accessibility
* Support for i18n (RTL)
This date selector can select between two dates

**Comment by fxck** [comment]
@yuxin6052 this is a pull request... you can see all the code in the files changed tab https://github.com/angular/material2/pull/1903/files

**Comment by jlno** [comment]
I did a pull of changes and settings the project `material2`, but after open `http://localhost:4200` the console says:

> Unhandled Promise rejection: Template parse errors:
> Can't bind to 'value' since it isn't a known property of 'md-input'.
> 1. If 'md-input' is an Angular component and it has 'value' input, then verify that it is part of this module.
> 2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Pull request closed without merging**
