### PR TITLE
fix(tooltip): remove tooltip component after it's parent destroyed

### LINKED ISSUE #1111: bug(md-tooltip): tooltip is not removed when parent is
Consider a scenario where there's a button inside a container. The button has a tooltip and on click it should set a variable to another value. Based on that value the container element is added / removed with `ngIf`. Simple example:

``` html
<div *ngIf="!hidden">
  <button
    md-button
    md-tooltip="Hide this button"
    tooltip-position="after"
    (click)="hidden = true">HIDE ME!</button>
</div>
```

After clicking the button the container div is removed, however, the tooltip remains still, no way to remove it.

[Plunkr example](http://plnkr.co/edit/GX8CnKNQ8Zlzm5Zras7r?p=preview).

### PR DESCRIPTION
**Pull request by gucheen**
fix #1111

### CODE REVIEW

**Comment by gucheen** [comment]
I signed it!

**Comment by jelbourn** [comment]
@gucheen could you add a unit test for this?

**Comment by gucheen** [comment]
Unit test has been added, but there was something wrong with the test scripts. 'gulp' was missing in travis.

**Comment by jelbourn** [comment]
@andrewseguin this may be obsolete based on your animation change, thoughts?

**Comment by jelbourn** [comment]
LGTM

**Pull request merged**
