### PR TITLE
chore: install Karma plugin so we can run on Safari

### PR DESCRIPTION
**Pull request by mmalerba**

### CODE REVIEW

**Comment by DevVersion** [comment]
Usually, only browsers that will be launched automatically or for the CI, should have the according launch plugin installed.

If you want to run on Safari though, we should run ´gulp serve:static` and just connect Safari manually. I don't care that much though. So I'm fine :smile:

**Comment by mmalerba** [comment]
@DevVersion does that allow us to run the tests on Safari? I just had a situation where I needed to manually inspect the unit tests on Safari and I couldn't figure out how to do it without adding this. Might just be me not knowing things though

**Comment by DevVersion** [comment]
@mmalerba Yeah, if you run `gulp serve:static` and open Safari & open that URL that is being printed in the terminal, the tests start to run (also with live-reload).

**Comment by mmalerba** [comment]
Ok, in that case I'll just close this one

**Pull request closed without merging**
