### PR TITLE
refactor: clean out variables that are being assigned to but not being read

### PR DESCRIPTION
**Pull request by crisbeto**
Clears out private properties and local variables that are declared and assigned values, but aren't actually being read at any point. This will start being caught by tslint once we update to TS 2.6.

### CODE REVIEW

**Comment by crisbeto** [comment]
tslint will start catching them when we update to TS 2.6 @mmalerba. I didn't bump to TS 2.6 in this PR, because there are some build issues that we'll need to sort out.

**Comment by josephperrott** [comment]
@crisbeto please rebase

**Comment by josephperrott** [comment]
Updating to `cla: yes` as the non-cla'd commit was done by me via github.

**Comment by crisbeto** [comment]
Rebased @josephperrott.

**Pull request merged**
