### PR TITLE
fix(paginator): change class name of increment and decrement icons

### PR DESCRIPTION
**Pull request by lharries**
Fix such that the previous page navigation button contains an icon with class decrement,
and the next page navigation button contains an icon with class increment. Previously
they were incorrectly swapped.

Noticed during fix for #9278

### CODE REVIEW

**Comment by tinayuangao** [comment]
@lharries Please rebase. 
Presubmit passes, after rebase it's ready to go.

**Comment by lharries** [comment]
@tinayuangao this has been fixed by #9603 which has now been merged so I'm not sure this PR is needed too?

**Comment by tinayuangao** [comment]
@lharries Just need to rebase to master and resolve the conflicts.

**Comment by lharries** [comment]
@tinayuangao it won't let me rebase as there are no changes to be made, as they have already been merged in #9603

**Comment by lharries** [comment]
I have managed to rebase, however as you can see there are no changes

**Comment by andrewseguin** [comment]
No worries, this can be closed since the changes were in the other PR.

**Pull request closed without merging**
