### PR TITLE
build: build material-examples with bazel

### PR DESCRIPTION
**Pull request by DevVersion**

### CODE REVIEW

**Comment by DevVersion** [comment]
It actually passed locally for me because I had the `example-module.ts` generated. This is not the case on the CI, so there are failures.

I will need to play more with it.. I'm considering using a `genrule` to build the file, but doesn't sound too good in the long-term.

**Comment by jelbourn** [comment]
I think we would _have_ to use a `genrule` because we really are generating a source file. It's pretty much exactly what genrule is meant for, even if it's usually discouraged.

**Comment by DevVersion** [comment]
Sounds good. Just interesting to see how we could run Gulp. Just having the logic as a single JS fils is probably easier.

**Comment by jelbourn** [comment]
Right- it's probably easiest to move it to a standalone script

**Comment by DevVersion** [comment]
@jelbourn I've finished the switch to a Bazel genrule. As mentioned on Slack, there were various things that slowed down this process because there were a few things I had to work around in favor of Windows.

This should be good now. Note that I didn't clean up too much of the existing AST parsing logic.. I've simplified the templating though.

**Pull request merged**
