### PR TITLE
Issue: Need Slider with values 0.1, 0.5, 1, 2, 5, 10, 15, 20, 30

### PR DESCRIPTION
**Pull request by AndreySyagrovskiy**
// Issue: Need Slider with values 0.1, 0.5, 1, 2, 5, 10, 15, 20, 30
// Solution: On some step it is possible to show value what we want

### CODE REVIEW

**Comment by AndreySyagrovskiy** [comment]
I signed it!

пн, 28 серп. 2017 о 00:20 googlebot <notifications@github.com> пише:

**Comment by mmalerba** [comment]
Maybe we can go with a display function as @willshowell mentioned in #4776? This would be more consistent with how we do it in autocomplete. Also needs tests

**Comment by AndreySyagrovskiy** [comment]
I #4776 <https://github.com/angular/material2/issues/4776> this idea!

ср, 30 серп. 2017 о 19:33 mmalerba <notifications@github.com> пише:

**Comment by AndreySyagrovskiy** [comment]
Do you need help or it is done by another peoples?

ср, 30 серп. 2017 о 19:36 Андрей Сягровский <syagrovskiyandriy@gmail.com>
пише:

**Comment by jelbourn** [comment]
Closing this as stale now

**Pull request closed without merging**
