### PR TITLE
feat(chips): support multi-select for chip-list component (#9097)

### PR DESCRIPTION
**Pull request by surfer19**
Hey guys,
I made few necessary changes also in logic of "focusing chips". 
See issue https://github.com/angular/material2/issues/9097#issuecomment-353786168
Now is working select/deselect chips in chips-demo.
Feel free to comment. ;)

### CODE REVIEW

**Comment by tinayuangao** [comment]
I think this is not we are going to do. Changing focus should not select/deselect a chip.

On our current chip list, you can add `(focus)=someCustomizedFunctionToSelectChip(chip)` and `[selected]=isChipSelected(chip)` to get the same result.

**Comment by surfer19** [comment]
@tinayuangao I followed comment of @tomasznastaly in issue "When we have multiple = true and selectable = true, then all clicked chips should have such border, then we know which ones are already selected". Is that wrong?

**Comment by tinayuangao** [comment]
@surfer19 Here's a stackblitz example to make a chip list with chips selected/deselected on focus:
https://stackblitz.com/edit/angular-2m74cb-3eyftd?file=app/chips-input-example.html

I don't think the default chip list should support select/deselect on focus.

**Comment by cnotv** [comment]
@tinayuangao your implementation triggers `ExpressionChangedAfterItHasBeenCheckedError`

**Pull request closed without merging**
