### PR TITLE
docs(expansions) create docs for expansions

### LINKED ISSUE #5568: Add docs for expansion-panel and accordion
We currently are missing documentation for expansion-panel / accordion. This needs:
- [ ] An overview file (`expansion.md`)
- [ ] At least two examples (typically one simple and one more in-depth)

The style of the overview should align with existing docs.

### PR DESCRIPTION
**Pull request by julianobrasil**
Fixes #5568.

### CODE REVIEW

**Comment by julianobrasil** [comment]
Sorry, I haven't seen the message to not modify example-module.ts at the top of the file. My bad. Restored it to Material/master's original state.

**Comment by julianobrasil** [comment]
@jelbourn, is there any problem to leave this PR with all these commits? Or should I remove it, rebase the code and submit a new PR? (my mistake - I'm used to work alone so I don't care about lots of commits, but I think here is different)

**Comment by jelbourn** [comment]
We squash them either way. You can also squash them yourself with `git rebase -i`.

**Comment by willshowell** [comment]
@julianobrasil [this article](http://matthew-brett.github.io/pydagogue/rebase_without_tears.html) is a great reference for rebasing

**Pull request closed without merging**
