### PR TITLE
chore(checkbox): fix style lint errors

### PR DESCRIPTION
**Pull request by belev**
r: @jelbourn

### CODE REVIEW

**Comment by jelbourn** [comment]
@belev Our build is green; are you using the latest version of `stylelint`?

**Comment by belev** [comment]
@jelbourn I am using the version which is on `master`. When I run `gulp lint` there is the following message: "Cannot parse selector". Maybe that is not an error but some kind of warning, I am not sure.

**Comment by jelbourn** [comment]
Did some poking around: this is a bug in `stylelint` 7.6.0:
https://github.com/stylelint/stylelint/issues/2093

Already fixed on their head, so we can just wait for the next release.

**Comment by belev** [comment]
Ah ok. Thanks for the information! :)

**Pull request closed without merging**
