### PR TITLE
docs(chips): remove example from component jsdoc

### LINKED ISSUE #6885: HTML error in Chips documentation
Page: https://material.angular.io/components/chips/api

The `<md-chip>` tags are not being closed:

```
<md-chip-list>
  <md-chip>Chip 1<md-chip>
  <md-chip>Chip 2<md-chip>
</md-chip-list>
```

### PR DESCRIPTION
**Pull request by andrewseguin**
Closes #6885

### CODE REVIEW

**Comment by willshowell** [comment]
Does it even make sense to have an example in the class comment? A nearly identical example is near the top of the overview.

https://material.angular.io/components/chips/overview

**Comment by andrewseguin** [comment]
It is rather redundant, I'm okay with removing it. What do you think @jelbourn - I don't think we include basic examples in other components

**Comment by jelbourn** [comment]
Yeah, we shouldn't have examples in the descriptions. Live examples are always better because we actually build them.

**Comment by andrewseguin** [comment]
SGTM - removed the example altogether

**Pull request merged**
