### PR TITLE
build(): Dartanalyzer travis

### PR DESCRIPTION
**Pull request by hansl**
Adding Dartanalyzer to travis. Please note this is branched off PR #69, which needs to be merged first.

### CODE REVIEW

**Comment by hansl** [comment]
@jelbourn please review. This enables the travis check.

**Comment by hansl** [comment]
The `Promise` changes is so we `process.exit()` properly. The analyzer code does not reject the promise when there's an error.

**Comment by hansl** [comment]
The only thing needed for this change here is the `ts2dart` Promise changes.

**Comment by jelbourn** [comment]
LGTM

**Pull request merged**
