### PR TITLE
chore(accordion): adds disabled property to CDK accordion-item (#8141)

### LINKED ISSUE #8141: [accordion]: add disabled property to CDK accordion-item
#### Proposal:

Move `common-behaviors` to CDK. 

#### What is the use-case or motivation for changing an existing behavior?

Accordion (and possibly other CDK components) need access to the `disabled` property on directives - see #7461

### PR DESCRIPTION
**Pull request by ouq77**
Adds a disabled property to Accordion Item in the CDK.

Closes #8141

### CODE REVIEW

**Comment by ouq77** [comment]
I signed it!

**Comment by jelbourn** [comment]
@ouq77 sorry if my comment on #8141 wasn't clear. I don't want to create a new subpackage in `@angular/cdk` for this type of behavior yet, as we don't have a well-defined set of features. What I meant instead was that we can just manually add the `disabled` property to the components.

**Comment by ouq77** [comment]
I think I misunderstood @jelbourn - will revert and apply to the component directly.

**Comment by josephperrott** [comment]
@ouq77 Correct

**Comment by ouq77** [comment]
Changes applied. Waiting for your feedback. :)

**Comment by ouq77** [comment]
@jelbourn and @josephperrott - yay for my 1st successful build! 😁

**Comment by ouq77** [comment]
Hi @jelbourn - any update on this PR? I've noticed you've been quite busy getting v5 out, so no worries.

**Comment by ouq77** [comment]
@josephperrott, I've been keeping this PR up to date with `master` - unfortunately, there are failing tests at the moment, but I don't think it's related. Hope you'll get around to it soon. Cheers.

**Pull request merged**
