### PR TITLE
test(button): add test for disabled input attribute

### PR DESCRIPTION
**Pull request by DevVersion**
Test for `disabled` input attribute in `md-button` component.

PS: If still PR's like this are not wanted, just close ;)

### CODE REVIEW

**Comment by hansl** [comment]
Could you rebase your changes on the latest master and let it run? Just added full unit tests to travis. Thanks!

**Comment by DevVersion** [comment]
@hansl Done ;) Tests are still passing

**Comment by hansl** [comment]
LGTM.

**Comment by hansl** [comment]
I'm going to merge this now for keeping the PR list clean.

**Comment by hansl** [comment]
Merge commit: 10d1e75bba2ff63ece4e97aebdae89837ebc0c82

**Pull request closed without merging**
