### PR TITLE
docs(form-field): set correct method name

### LINKED ISSUE #9370: Typo in guide: "Creating a custom form field control"
#### Bug, feature request, or proposal:

Typo

#### What is the expected behavior?

`setDescribedByIds(ids: string[])`

#### What is the current behavior?

`setAriaDescribedByIds(ids: string[])`

#### What are the steps to reproduce?

https://material.angular.io/guide/creating-a-custom-form-field-control#-code-setariadescribedbyids-ids-string-code-

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

5.0.4

### PR DESCRIPTION
**Pull request by donroyco**
This fixes #9370

### CODE REVIEW

**Comment by julianobrasil** [comment]
Shouldn't it be better to change the function name to `setAriaDescribedByIds`?

**Comment by donroyco** [comment]
@julianobrasil Could've gone both ways.

**Comment by julianobrasil** [comment]
Thinking of it for a second, I can't remember right now where, but I have already seen functions in material library that deals with accessibility and don't mention it in their names.

**Comment by donroyco** [comment]
@julianobrasil Thanks for getting back on this.

**Pull request merged**
