### PR TITLE
fix(tooltip): remove native event listener on component destroy

### LINKED ISSUE #4499: Tooltip Memory Leak
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
For tooltip to not leak memory.

#### What is the current behavior?
Tooltip seems to leak memory.

#### What are the steps to reproduce?
**Plunker with tooltip:**
https://plnkr.co/edit/IFpa3W9EXGG1Mch7TBmm?p=preview

**Plunker without tooltip**
https://plnkr.co/edit/vFdyEmedUYGCavMl8eEN?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Used plunker template provided in issue template, so latest.

#### Is there anything else we should know?
I performed a devtools timeline recording and tried to keep it apples-to-apples. I performed GC at the start and end of each recording.

Strangely, both recordings seem to indicate leaking DOM nodes, which aren't cleaned up after a GC. The version with the tooltip however, doesn't clean up after itself nearly as nicely as the version without it.

**Timeline Without Tooltip**
without-tooltip

**Timeline With Tooltip**
with-toolitp

### PR DESCRIPTION
**Pull request by michastreppel**
Component should clean up events it has registered to.

Closes #4499

### CODE REVIEW

**Comment by willshowell** [comment]
cc @andrewseguin

**Comment by kara** [comment]
@michastreppel  Can you rebase this so we can merge?

**Comment by michastreppel** [comment]
Changes are now in PR#5144

**Comment by jelbourn** [comment]
#5144

**Pull request closed without merging**
