### PR TITLE
Please start providing context for nuanced config settings.

### PR DESCRIPTION
**Pull request by megamindbrian**
Every config I have seen lacks context.  When dealing with complex configs, we need to start providing the settings around the configuration options of interest in case other passer-bys are looking for where to include these specific and nuanced settings.  This is the only page that talks about scss being used in angular-cli.json

### CODE REVIEW

**Comment by megamindbrian** [comment]
@mmalerba Why is travis-ci linter failing? This isn't a code change it's a documentation change.

**Comment by mmalerba** [comment]
@megamindbrian looks like a lint error that was accidentally merged into master a while back. It has since been fixed and will probably go away if you rebase

**Comment by megamindbrian** [comment]
@mmalerba How do I rebase a commit made through Githubs editor?  All the changes are stored online so I don't have a separate branch.  How do I checkout ```megamindbrian:patch-1``` when it doesn't show in the history?
Looks like you can do this:
image

**Comment by mmalerba** [comment]
I'll just ignore the lint issue warning merge after this is LGTM'd, since it's clearly unrelated to your changes

**Comment by jelbourn** [comment]
I don't think this is the place to describe what the config file should look like; that level of detail belongs to the angular-cli documentation

**Comment by megamindbrian** [comment]
You're wrong.  What is there is meaningless without context.  Showing that
the angular/material2 theme can be imported by the styles: [] section of
config is your responsibility since it is already on the page, and it is
meaningless without context.  It's also hard to read the way it currently
exists.

**Comment by willshowell** [comment]
> If you are using the Angular CLI, support for compiling Sass to css is built-in; you only have to add a new entry to the `"styles"` list in `angular-cli.json` pointing to the theme file (e.g., `unicorn-app-theme.scss`).

@megamindbrian what context is missing? That paragraph tells you
1. What entry you need to add
2. What file you need to add it to
3. Where in that file you should add it

The only improvement I could see is changing `angular-cli.json` to `.angular-cli.json` to match recent cli updates.

**Comment by megamindbrian** [comment]
Where is styles?

**Comment by willshowell** [comment]
> in `angular-cli.json`

**Comment by megamindbrian** [comment]
```
{
    "apps": [
        {
            "name": "unicorn-app",
            ... main, polyfills, etc
        },
        "styles": [
            "unicorn-app-theme.scss"
        ]
    ]
}
```

```
{
    "apps": [
        {
            "name": "unicorn-app",
            ... main, polyfills, etc
        }
    ],
    "styles": [
        "unicorn-app-theme.scss"
    ]
}
```
```
{
    "defaults": {
        "styles": [
            "unicorn-app-theme.scss"
        ]
    }
}
```

```
{
    "project": {
        "styles": [
            "unicorn-app-theme.scss"
        ]
    }
}
```

**Comment by megamindbrian** [comment]
@willshowell This is why people can't trust open source.

**Comment by megamindbrian** [comment]
https://github.com/angular/material2/pull/6530

**Comment by megamindbrian** [comment]
https://github.com/angular/material2/issues/4125#issuecomment-318893710

**Comment by megamindbrian** [comment]
Because even people working for Google hate writing documentation.

**Pull request closed without merging**
