### PR TITLE
build: add tslint rule for consistent file name casing

### PR DESCRIPTION
**Pull request by crisbeto**
Adds a tslint rule to enforce that the casing on our filenames is consistent. The tslint rule files are excluded, because their names have to be in camel case and end with `Rule`.

### CODE REVIEW

**Comment by crisbeto** [comment]
I did it because:

* The logic is pretty simple and I doubt we'd need to do much maintenance on it.
* We have a lot of rule files. Aside from the custom tslint rules, we also have the schematic rules. That means having to add those disable comments in a lot of places and having to remember to do it whenever another gets added.

**Comment by devversion** [comment]
I see your point, but I'm hesitant because we can simply avoid having another rule.

1) The logic is simple, but just adding `// tslint:disable-rule:file-name-casing` only to our custom rules seems simpler to me (47loc vs ~5loc)
2) We can still do that with the approach above 
3) True, but if we forget about it, `tslint` will automatically show it as an failure and we'll know about it. Also most likely all rules are copy-pasted from an existing rule.

It just feels wrong to me to add a custom rule for something that can be easily replaced by an official rule. Especially since that's basically why `tslint`'s disable comment feature exists.

**Comment by crisbeto** [comment]
It not just 5 files though. These are the files that would fail the check:

```
attributeSelectorsStringLiteralRule.ts
attributeSelectorsStylesheetRule.ts
attributeSelectorsTemplateRule.ts
classInheritanceCheckRule.ts
classNamesIdentifierRule.ts
cssSelectorsStringLiteralRule.ts
cssSelectorsStylesheetRule.ts
cssSelectorsTemplateRule.ts
elementSelectorsStringLiteralRule.ts
elementSelectorsStylesheetRule.ts
elementSelectorsTemplateRule.ts
inputNamesStylesheetRule.ts
inputNamesTemplateRule.ts
checkTemplateMiscRule.ts
outputNamesTemplateRule.ts
propertyNamesAccessRule.ts
constructorSignatureCheckRule.ts
methodCallsCheckRule.ts
checkClassInheritanceMiscRule.ts
checkClassNamesMiscRule.ts
checkImportsMiscRule.ts
checkPropertyNamesMiscRule.ts
checkTemplateMiscRule.ts
rippleSpeedFactorAssignmentRule.ts
rippleSpeedFactorTemplateRule.ts
missingRollupGlobalsRule.ts
noExposedTodoRule.ts
noHostDecoratorInConcreteRule.ts
noImportSpacingRule.ts
noPrivateGettersRule.ts
noUnescapedHtmlTagRule.ts
requireBreakingChangeVersionRule.ts
requireLicenseBannerRule.ts
rxjsImportsRule.ts
settersAfterGettersRule.ts
validateDecoratorsRule.ts
```

It'll start looking even weirder when we have to start placing that `tslint:disable` comment on top of some of these files that have a license header. It's pretty easy to miss the error in your IDE, because it only highlights the first character of the file.

**Comment by devversion** [comment]
Ah I didn't realize that this also affects the schematic rules because I thought we exclude the `ng-update` folder within `tslint.json`.

It's true that it's easier to maintain the rule instead of a list like that then.

**Comment by devversion** [comment]
Actually the official tslint rule landed support for custom filename casing a few days ago. 

See: https://github.com/palantir/tslint/commit/a43cfdc4534c63447a6a5a66a6802716892503d2

This could spare us the additional custom rule and we can still get all benefits from a custom rule. It's just not released yet. I'm fine getting this in the meanwhile even though it's not urgent, or we just wait.

**Comment by crisbeto** [comment]
I've left in a TODO to consider replacing the rule once those changes are released.

**Pull request merged**
