### PR TITLE
build: add 'prefer-const' tslint rule

### PR DESCRIPTION
**Pull request by rafaelss95**

### CODE REVIEW

**Comment by rafaelss95** [comment]
**Note:** This PR is here to ask if you're interested in adding this rule. If so, I can go ahead and fix all the incoming lint issues.

CC @jelbourn.

**Comment by jelbourn** [comment]
While I agree we should prefer `const`, I'm concerned about the huge number of line changes this would cause. It would end up causing a lot of merge conflicts without providing any major value

**Comment by rafaelss95** [comment]
@jelbourn  Indeed. Maybe try to fix component by component (step by step) or just close this PR?

**Comment by jelbourn** [comment]
I'd be okay with just closing since I don't think the preference for `const` over `let` makes a big enough difference to bother

**Pull request closed without merging**
