### PR TITLE
fix(MdSidenavLayout): Remove deprecated @View

### PR DESCRIPTION
**Pull request by gdi2290**
@View was removed in beta.11
https://github.com/angular/angular/commit/f9fb72fb0e9bcbda7aeebbf8321ce5d70d78ecee

### CODE REVIEW

**Comment by jelbourn** [comment]
LGTM

**Comment by gxclarke** [comment]
I encountered this issue due to using a version after beta.10. I'm pulling the files into my project via NPM. Do you publish a nightly build to NPM, or do I need to wait for a new material2 release (or manually update from this repo)?

**Comment by jelbourn** [comment]
@gxclarke we don't have a night / per-commit snapshot set up yet; for now I'd recommend waiting until the alpha.2 release.

**Comment by ojacquemart** [comment]
Is it possible to publish an alpha.1.1 to make the lib compatible with the versions >= beta.11?
I understand that this is part of the alpha game but it will be pretty cool :)

**Pull request closed without merging**
