### PR TITLE
feat(select): expand md-select width to displayed option size

### LINKED ISSUE #2234: md-select width issue
#### Bug, feature request, or proposal:
md-select width is always 112px, whatever the size of the displayed option

#### What is the expected behavior?
When the selected option is wider than the md-select, the md-select should resize accordingly

#### What is the current behavior?
The md-select has a fixed width

#### What are the steps to reproduce?
See plunker here:
https://plnkr.co/edit/eMIni8u4rBzJj07bKRJQ?p=preview

Default selected value is very long, the down arrow is in the middle of the text.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-alpha.11-3
Tested with chrome 55.0.2883.87 , firefox 51.0b7

### PR DESCRIPTION
**Pull request by alexbeattie42**
Make the select box expand to the size of its selected option.  
Set lower minimum width and higher maximum width.
Handle label width when it has no value.
Remove now invalid test cases.

Closes #2234

### CODE REVIEW

**Comment by alexbeattie42** [comment]
I signed it!

**Comment by jelbourn** [comment]
Closing this since it's become quite stale. Feel free to open a new PR if this is still relevant.

**Comment by alexbeattie42** [comment]
Could the Angular Material 2 maintainers explain why this pull request received no feedback, was ignored for many months, and is now closed given it fixes a current issue in Angular Material 2. @jelbourn

**Comment by jelbourn** [comment]
This particular PR looks like it was just missed by the team when it was opened. It was before github had CODEOWNERS that automatically sent emails for new PRs.

**Comment by alexbeattie42** [comment]
Is there interest in fixing this issue? @jelbourn

**Comment by jelbourn** [comment]
It depends on the approach. It would have to be something non-breaking that is still conformant with people's general expectations and the Material Design spec.

**Pull request closed without merging**
