### PR TITLE
Correctly show the correct position option

### PR DESCRIPTION
**Pull request by chrishawn**
Correctly show the correct position option in the example

### CODE REVIEW

**Comment by belev** [comment]
@andrewseguin added the labels that it is ready for merge, but isn't it better before that to change the commit message according to the [Commit Message Guidelines](https://github.com/angular/material2/blob/master/CONTRIBUTING.md#commit) ?

**Comment by andrewseguin** [comment]
Commit message is changed when we merge, but removed the label for the sake of the cla:no

**Comment by andrewseguin** [comment]
Made the change in #2104. Thanks for pointing out the typo

**Comment by chrishawn** [comment]
Tried to fill out CLA page was broken didn't allow me to submit kept saying I was missing data when I wasn't

**Comment by belev** [comment]
@andrewseguin ah, ok. Thanks for clarifying!

**Pull request closed without merging**
