### PR TITLE
fix: Get correct viewport dimensions in ConnectedPositionStrategy

### PR DESCRIPTION
**Pull request by isaacplmann**
Should get viewport dimensions using `window.innerWidth`/`window.innerHeight` instead of `document.documentElement.clientWidth`/`document.documentElement.clientHeight`.

### CODE REVIEW

**Comment by isaacplmann** [comment]
It miscalculates the `bottom` style when the `<body>` is scrollable and the overlay needs to be placed above the origin point.  I'm working on a reproduction repo.

**Comment by isaacplmann** [comment]
Code:
https://github.com/isaacplmann/ngx-contextmenu

Running Demo:
https://isaacplmann.github.io/ngx-contextmenu/

Steps to reproduce:
1. Shrink your browser height so that right-clicking on an item would make the context menu overflow the bottom of the viewport.
2. Right-click that item

Expected results:
The context menu is rendered above the point you clicked.  i.e. Style is something like `bottom: 36px`

Actual results:
The context menu is rendered above the top of the viewport.  i.e. Style is something like `bottom: 1086px`

That bottom value is the distance from the bottom of document, but is being rendered that distance from the bottom of the viewport.  This could alternatively be fixed like this:
```html
<html style="position:relative">
  <div class="cdk-overlay-container" style="position: absolute">
```
But that alternative will probably break other things.

Relevant code in my library is here:
https://github.com/isaacplmann/ngx-contextmenu/blob/master/src/lib/contextMenu.service.ts#L68

I'd be really happy to find out that I'm just doing it wrong.

**Comment by isaacplmann** [comment]
I see what you're referring to about scrollbars messing up the calculation.  I think what we really want is to use the height and width of the `.cdk-overlay-container` and not `window.innerHeight` or `document.documentElement.clientHeight`

**Comment by isaacplmann** [comment]
I've discovered the problem.  I wasn't including `<!doctype html>` at the top of the `index.html` file.  For some reason that causes `document.documentElement.clientHeight` to return the height of the document content, rather than the height of the viewport.  That's a very non-obvious solution to a positioning problem.  Using the height/width of the `.cdk-overlay-container` would solve this regardless of the doctype.

**Comment by crisbeto** [comment]
This isn't the only issue caused by not including a doctype though. Material actually logs a warning if your document doesn't have a doctype, but you might have missed it if you've silenced console warnings.

**Comment by isaacplmann** [comment]
Ok. Then perhaps the right solution is to have cdk log a warning as well.
My library doesn't use material, just the cdk.

**Comment by isaacplmann** [comment]
I'll open an issue to have the cdk warn when not using the correct doctype.  Closing this PR.

**Pull request closed without merging**
