### PR TITLE
fix(tooltip): exception if mdTooltip is not a string

### PR DESCRIPTION
**Pull request by rafaelss95**
Fixes an error that is thrown if something rather than a string is passed via [mdTooltip] `@Input`, i.e:

```
@Component({
  selector: 'some-selector',
  template: '<div [mdTooltip]="myNumber">Content</div>'
})
export class SomeClass {
  
  myNumber = 3;
}
```

Results in the following error:

> this._message.trim is not a function

[PLUNKER](https://plnkr.co/edit/MlMcOXMzUEItNTIQzDur?p=info)

### CODE REVIEW

**Comment by crisbeto** [comment]
Can you add a unit test for this?

**Comment by rafaelss95** [comment]
@crisbeto  I can't do this. It gives me error (the method signature asks for a string): 

> Type '{}' is not assignable to type 'string'.

**Comment by crisbeto** [comment]
You can change the testing component signature to something like `string | null`.

**Comment by rafaelss95** [comment]
I'm not sure I follow what you mean. `tooltipDirective` is an instance of `MdTooltip` and there the signature of `set message(..)`  accepts (only) a string:

```
 set message(value: string) {
   this._message = value;
   this._setTooltipMessage(this._message);
 }
```

**Comment by crisbeto** [comment]
I was talking about one of the test components here: https://github.com/angular/material2/blob/master/src/lib/tooltip/tooltip.spec.ts#L523

**Comment by rafaelss95** [comment]
Changing `message` to `any` still fail.

**Comment by rafaelss95** [comment]
Closing due to #7018 and #7024. :)

**Pull request closed without merging**
