### PR TITLE
feat(text-field): text-field creation (no styles)

### PR DESCRIPTION
**Pull request by gbataille**
Hi, I had a mind to try and contribute to material2

This PR is nowhere near ready but I was wondering if you were interested.

If so I have a few of questions
* I had based myself on the md-button attribute directive, but I think in this case I should do something more like the md-card component. Agreed?
* for text-field, you need label and input to be linked by their id. I propose to use a uuid. any thoughts?
* I have had problems with the ts2dart transpiler. for uuid, I originally used the full code of angular2-uuid. But it was using `typeof` that does not seem supported. Any comment on that. Do you find that's a blocker sometimes?
* I had originally put the uuid code in a separate helper class/file. the ts2dart compiler complained of syntax issues where it generated some `library 'folder_name'; class uuid` kind of syntax (I know nothing about dart). Does that ring a bell? Was I doing something wrong?

That's all for a first pass :)

Remark: the jasmine tests don't seem to pass on a fresh check-out of the code. Some sidenav tests are failing

### CODE REVIEW

**Comment by zoechi** [comment]
With more concrete information about errors or the behavior I might be able to provide some assistance. I know Dart well but not ts2dart though.

**Comment by gbataille** [comment]
Well I used a reasonnable enough workaround. But I'll create a branch for
you on my repo so you can see what I'm saying
I'll try to do that tonight.
Cheers

**Comment by jelbourn** [comment]
@gbataille Please read our [contributing guidelines](https://github.com/angular/material2/blob/master/CONTRIBUTING.md#-want-a-feature). I'm super happy you're excited to be contributing, but it's important that we follow the process there so that we're all on the same page before any code is written. In the future, please open an issue for discussion before working on a PR for a major feature (such as a new component). 

For inputs in particular, the team is currently working on a design for how to handle all input types (autocomplete, dates, etc.) in a uniform way that may involve changes to Angular 2 itself, so it's not the best area for contribution at this time.

**Comment by gbataille** [comment]
Hey @jelbourn yeah I guessed as much. I actually read most of the CONTRIBUTING article, but jumped quickly to the PR part.

So is there any area where you want some external, few hours a week help, or it's a bit too early? I'm actually a bit lost as to how to enter :)

Cheers

**Comment by jelbourn** [comment]
@gbataille it is still early, since we haven't finished getting our infrastructure and tooling set up yet. 

Check out our issues; there will be some that are good for community contributions, such as #85

**Pull request closed without merging**
