### PR TITLE
fix(text-field): add fallback for browsers that don't support requestAnimationFrame

### PR DESCRIPTION
**Pull request by crisbeto**
Currently we've got a block in the autosize textarea that depends on `requestAnimationFrame`, however it won't run if it isn't supported, which means that the fix it's applying won't run on some browsers. These changes add a fallback via `setTimeout`.

### CODE REVIEW

**Comment by mmalerba** [comment]
What browsers don't support requestAnimationFrame?

**Comment by crisbeto** [comment]
IIRC it’s some of the older IEs and Angular Universal. I did it it primarily for consistency since it’s what we do everywhere we use requestAnimationFrame, but it’s fine if you think that we should close this one.

**Comment by mmalerba** [comment]
We should find out if Angular Universal still doesn't support this, I would think it does. And I know IE11+ supports it, so we don't have to worry there

**Comment by crisbeto** [comment]
I just tried logging out `requestAnimationFrame` in the kitchen sink app I got this:

```
ERROR { ReferenceError: requestAnimationFrame is not defined
```

**Pull request merged**
