### PR TITLE
Docs (Snack-Bar): show how to do a self reference with a snack bar

### LINKED ISSUE #3002: Unclear documentation about snackbar usage on documentation website
#### Bug, feature request, or proposal:
Documentation: Snackbar component is unclear, and its Plunker code example is not running

#### Details:
1. It seems the Snackbar component documentation on website does not describe fully about how to open snackbar from component and what to do with `MdSnackBarRef` in API Reference tab while they are mentioned in Overview tab

2. Plunker example in Examples tab of Snackbar component is not working.
    *Reproduce steps:*
    - Initial Plunker example when clicking Edit in Plunker: https://plnkr.co/edit/mH5Hh14TZAD3WH2AlU2x?p=preview
    - Click Pizza Party button, the snackbar does not appear

    *Notes:*
    - Developer need to add `PizzaPartyComponent` in `declarations` and `entryComponents` of `ngModule` in `main.ts` file, plus create new template `snack-bar-component-example-snack.html` and component stylesheet `snack-bar-component-example-snack.css` for `PizzaPartyComponent`.
    - Plunker example: https://plnkr.co/edit/IVRsaVTFRiaHIHGXnhAw?p=preview

3. The documentation does not describe how to execute the action of a component itself if that component is opened in snackbar.
In the project source code, I've found that to execute the dismiss snackbar action when open snack bar from `open` method you guys did this:
- Create a self-reference with `MdSnackBarRef` of the content component: In class `SimpleSnackBar`, there is `snackBarRef: MdSnackBarRef<SimpleSnackBar>` property. To be able to dismiss snackbar, `SimpleSnackBar` component has to call `dismiss()` method, which in turn calls the `_action()` method of `snackBarRef`.
- In `open` method of `MdSnackBar`:
```javascript
open(message: string, action = '', config: MdSnackBarConfig = {}): MdSnackBarRef<SimpleSnackBar> {
    config.announcementMessage = message;
    let simpleSnackBarRef = this.openFromComponent(SimpleSnackBar, config);
    simpleSnackBarRef.instance.snackBarRef = simpleSnackBarRef;
    simpleSnackBarRef.instance.message = message;
    simpleSnackBarRef.instance.action = action;
    return simpleSnackBarRef;
}
```
At `line 4`, the `snackBarRef` of instance `SimpleSnackBar` of `simpleSnackBarRef` was assigned to `simpleSnackBarRef` itself. Therefore, the snackbar component was able to close.

If I want to create a snackbar from a component with a dismiss/arbitrary button, then I have to do the same with my code. However, there is no instruction to do that with `openFromComponent` method. I think this should be documented clearer so developer can do that from looking at the documentation, not have to dig into the source code.
Plunker example: https://plnkr.co/edit/rOql4ebj2d5ynQpzutUW?p=preview

#### Which versions of Angular, Material, OS, browsers are affected?
Material: 2.0.0-beta1

### PR DESCRIPTION
**Pull request by M-a-c**
showed how to do a self reference in the Snack-Bar docs
Fixes #3002

### CODE REVIEW

**Comment by M-a-c** [comment]
I could create an example for this instead of inlining it, if that is prefered.

**Comment by xuanshenbo** [comment]
Possibly also add an example of using extraClasses property? It took me a while to understand what it does.

Something like - extraClasses: 'red' will add the .red css class to the snack bar component?

**Comment by M-a-c** [comment]
@xuanshenbo can you make a new issue for this? It doesn't fall under the scope of showing how to use a self reference.

**Comment by xuanshenbo** [comment]
@M-a-c Yes you are right. I'll do that

**Comment by jelbourn** [comment]
Closing this since it's gone quite stale. Feel free to reopen a new PR if the content is still relevant.

**Pull request closed without merging**
