### PR TITLE
feat(overlay): add ability to set custom class on panes

### PR DESCRIPTION
**Pull request by fxck**
I re-did https://github.com/angular/material2/pull/1438 

It includes tests for overlay(I didn't see any similar tests for say backdrop class on menu or dialog, so I assumed it's not required since it should inherently work when overlay tests passes) and comments from the previous PR with the exception of https://github.com/angular/material2/pull/1438#discussion_r84730695 and https://github.com/angular/material2/pull/1438#discussion_r84734492 which didn't make sense to me.

@jelbourn

### CODE REVIEW

**Comment by jelbourn** [comment]
@fxck Would your specific problem be solved by simply having a higher z-index on the overlay container? (right now it's just 1 to create a new stacking context).

**Comment by fxck** [comment]
No, unless I were in control of that z-index. But what might be worth doing is sticking that custom class on container rather than pane. I'm not sure what was the original reasoning for putting it on panes, it's been a while.

**Comment by fxck** [comment]
I see, the reason why I added it to `pane` instead of `container` was that there is only one `container`. 

Then there's this ..

image

..when you open, menu from inside a dialog, the stacking order is not correct, dialog itself it above menu's backdrop. 

I think is issue is a bit deeper, there should be some sort of stacking order manager.

@jelbourn @kara

**Comment by crisbeto** [comment]
Are there any plans to continue with this PR? Something similar (being able to add a class to the `.overlay-pane`) should help with an issue where the tooltip can sometimes become hidden immediately.

**Comment by fxck** [comment]
I never got the reply about stacking manager. I think adding classes to either pane or overlay would be only a temporary fix and more issues will come up sooner or later. But I don't want to do anything without having a discussion.

**Comment by jelbourn** [comment]
This has been on the backburner since I've been wanting to spend some more time thinking about how stacking should work in general.

**Comment by fxck** [comment]
Stacking aside, this still could be useful, currently there's no way to properly style md-menu(stuff like `width`).

**Comment by fxck** [comment]
I take it back, there is, it has to be global though.

**Comment by mmalerba** [comment]
@jelbourn @fxck what's the status of this should it be rebased? closed?

**Comment by fxck** [comment]
for what it was, this PR is obsolete, altho most of my points stands, there still are cases when inability to control z-index of panes and overlays still can cause problems, as well as I think there needs to be a class that handles z-index of various elements.

**Comment by mmalerba** [comment]
@fxck ok will close this PR then, if you have concerns about z-index that aren't already being tracked by an issue, feel free to open a new issue to discuss them.

**Pull request closed without merging**
