### PR TITLE
Revert "fix: workaround for es2015 inheritance not always working (#1…

### PR DESCRIPTION
**Pull request by jelbourn**
…3834)"

This reverts commit a22a9fa3d737b423206e26b3afea8c556270238c.

This change caused a new issue where Closure Compiler was not able to do
dead-code elimination due to the function call with unknown side
effects.

### CODE REVIEW

**Comment by DevVersion** [comment]
@jelbourn Hmm going forward with this, I'm not sure if it's even worth keeping the workaround at all. 

The way it's right now (without my new changes), it's practically *not helping* and just causes even more exceptions than before (in case the `ctorParameters` are not a function; which is often the case). 

We definitely need to solve the Closure issue, and I can't think of a way to mark the _function_ for inheriting as side effect free (https://github.com/google/closure-compiler/issues/2256). That being said, we should probably remove the workaround completely and wait for Ivy. It's not an issue from Material, rather from Angular.

**Comment by DevVersion** [comment]
Also considering that https://github.com/angular/angular/pull/24014 is finally merge ready as well, it might be just the best to get rid of the workaround completely.

**Comment by jelbourn** [comment]
We need to revert it first to unblock syncing into Google and then we can explore other approaches

**Comment by jelbourn** [comment]
@DevVersion yeah, let's discuss it in more detail

**Pull request merged**
