### PR TITLE
chore(radio): change declaration of MatRadioChange class

### LINKED ISSUE #8791: About removing `| null` from `source` property declaration
#### Bug, feature request, or proposal:
Maybe a bug.

#### What is the expected behavior?
Just remove `| null` from declaration.

#### What is the current behavior?
Look at these classes:

https://github.com/angular/material2/blob/5210b3e197647381611ec48ddcd99333ec5356e9/src/lib/radio/radio.ts#L62
https://github.com/angular/material2/blob/5210b3e197647381611ec48ddcd99333ec5356e9/src/lib/button-toggle/button-toggle.ts#L57

I don't see how the `source` property of these `events` can be null.

I'm concerned about this because if `--strictNullChecks` is enabled in some application (as it's on mine) and we try to access any property of `source` we can't do this directly, like this:

```
someFunc(matButtonToggleChange: MatButtonToggleChange) {
  matButtonToggleChange.source.<ANY_PROPERTY>;
}
```

... you just received the following error from typescript: 

> Object is possibly 'null'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.5
Node: 8.1.1
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.5
@angular/material-moment-adapter: 5.0.0-rc.2
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.6.2
webpack: 3.8.1
```

### PR DESCRIPTION
**Pull request by rafaelss95**
Partially address #8791.

### CODE REVIEW

**Comment by crisbeto** [comment]
The button toggle changes were made as a part of https://github.com/angular/material2/pull/9191.

**Comment by rafaelss95** [comment]
@crisbeto will you make the change (declare source as `MatToggleButton` only instead of `MatToggleButton | null` in `button-toggle` in that PR? If so I can revert it here and ler only the radio changes.

**Comment by crisbeto** [comment]
Done.

**Comment by rafaelss95** [comment]
@crisbeto Done. I just kept the change related to `radio`.

**Pull request merged**
