### PR TITLE
build: restructure demo-app in favor of bazel

### PR DESCRIPTION
**Pull request by DevVersion**
Restructures the demo-app by no longer mixing up the `demo-app` name.

Currently the `demo-app` consists of two parts:

  * The demo-app
  * And the accessibility demos

As you can tell above, this is pretty much confusing because it's
technically just consisting of:

  * Accessibility demos
  * Library demos

This change cleans up the naming and makes sure that the modules are
structured in a best-practice way.

It's odd to have the `DemoAppModule` (*not the root module*) that
includes all library demos as a folder next to the actual demo
components.

This makes it extremely hard to convert the demo-app to Bazel because
we cannot target all `.ts` files through `glob` because it only matches
files inside of the same folder (or Bazel package).

In order to make it easy to run the demo-app with Bazel, and to just
clean it up, the folder structure should be as followed:

```
src/a11y-demo/
  | ...

src/dev-app/
  | ${DEMO_COMPONENT}
     | ...
     | BUILD.bazel
  | index.html
  | BUILD.bazel
```

### CODE REVIEW

**Comment by DevVersion** [comment]
That works too, and I considered it as well, but I just was afraid of re-adding another gulp process for the `a11y` app which should probably also include a watch mode, and build configuration.

I'm fine doing so though. We can also just have the `a11y` app as a plain Bazel package. While it would still take some time to actually serve it with Bazel, we could already build it like that.

I suppose nobody is currently spending a lot of time on the `a11y` demos anyway.

**Comment by jelbourn** [comment]
Yeah, I would prefer splitting out the a11y app into a separate thing. Also, since it's such a big change anyway, renaming `demo-app` to `dev-app`.

**Comment by DevVersion** [comment]
@jelbourn That's reasonable. Should we still add gulp tasks for the `a11y` stuff or rather just use Bazel for building (as mentioned above)?

**Comment by jelbourn** [comment]
We can just do the bazel setup for now since nobody is actively using the a11y demos at the moment

**Comment by DevVersion** [comment]
Sounds good. That's what I was hoping. I will make the changes as soon as possible.

**Comment by DevVersion** [comment]
@jelbourn I've updated the PR.

**Comment by jelbourn** [comment]
To clarify: the intent of this change is to make it _possible_ to run the dev-app via bazel, which will be a follow-up, right?

**Comment by DevVersion** [comment]
Exactly. There are a few more blockers for actually building the dev-app with Bazel, but I'm working on fixing those (e.g. https://github.com/angular/angular/pull/27062)

This PR should be ready for review.

**Comment by DevVersion** [comment]
@andrewseguin This one is rebased now as well. 

It's just red because of the API guardian tests. Those should be fixed with #14144.

**Pull request merged**
